### ISSUE TITLE
Wrong download query is generated when placing wildcard at the end

### ISSUE THREAD

**Issue by yoshaul** [JFrogDev/jfrog-cli-go#1]
for example jfrog rt dl releases/jfrog.com/test/server/server*
Generated the following query: 
`items.find({"repo": "releases","$or": [{"$and": [{"path": {"$match":"jfrog.com/test/server"},"name":{"$match":"server*"}}]},{"$and": [{"path": {"$match":"jfrog.com/test/serverserver"},"name":{"$match":"*"}}]}]})`

Note the "serverserver"

**Comment by eyalbe4** [comment]
Thank you for reporting this.
This issue has been fixed. The code has been committed to branch 1.1 and will be included as part of the release 1.1.

**Comment by eyalbe4** [comment]
The fixed is included in the latest release.
