### ISSUE TITLE
Current stable version?

### ISSUE THREAD

**Issue by ilovezfs** [JFrogDev/jfrog-cli-go#102]
Based on https://github.com/JFrogDev/jfrog-cli-go/releases and https://github.com/JFrogDev/jfrog-cli-go/releases/latest I cannot tell if 1.11.1, 1.11.0, or something else besides either of them, is the current stable version.

Which version should be in Homebrew's stable spec? Thanks!

**Comment by eyalbe4** [comment]
We apologies about this @ilovezfs!
We've just created a release for [1.11.1](https://github.com/JFrogDev/jfrog-cli-go/releases/tag/1.11.1). 
This is currently the latest JFrog CLI release.

**Comment by ilovezfs** [comment]
@eyalbe4 no worries! Thank you for clarifying. In that case, I will merge https://github.com/Homebrew/homebrew-core/pull/18938.
