### ISSUE TITLE
jfrog rt build-publish env-exclude defaults should ignore case

### ISSUE THREAD

**Issue by mfriedenhagen** [JFrogDev/jfrog-cli-go#105]
On Linux environment variable names are normally uppercase. So I normally use sth. like `TOOLUSER_NAME=foo` and `TOOLUSER_PASSWORD=bar`. While `build-publish` excludes the lowercase variant `tooluser_password` by default, it unfortunately publishes `TOOLUSER_PASSWORD`.

So my suggestions would be to either:
a) extend the default: `*password*;*secret*;*key*;*PASSWORD*;*SECRET*;*KEY*`
b) or lowercase the variable names before matching.

If you want to make me really happy, include `*TOKEN*;*token*` as well ;-)

**Comment by eyalbe4** [comment]
Thanks for suggesting this @mfriedenhagen.
We'll make the environment variables exclusion case insensitive and will also add *token* to the list of default excluded patterns.
We'll let you know when this is implemented.

**Comment by romangurevitch** [comment]
@mfriedenhagen,
Thank you for opening this issue, we committed a fix for the problem which will be included in our upcoming release.

**Comment by eyalbe4** [comment]
@mfriedenhagen,
The latest release includes this fix. We'd appreciate your feedback for it.
We've also updated the [documentation](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-BuildIntegration-PublishingaBuild) to state that the list of pattern is case insensitive. We'll make sure to also update the command help with the next release.

**Comment by mfriedenhagen** [comment]
Thanks, I already tested this, seems to work :-)
