### ISSUE TITLE
jfrog rt set-props --include-dirs flag doesn't work

### ISSUE THREAD

**Issue by r631269** [JFrogDev/jfrog-cli-go#106]
the `--include-dirs` flag doesn't seem to do anything

With `--include-dirs`
`jfrog rt set-props --include-dirs=true "some-repo/some-dir/" "a=1,b=2,3"`
```
[Debug] Searching Artifactory using AQL query:
 items.find({"repo": "some-repo","path": {"$ne": "."},"$or": [{"$and":[{"path": {"$match": "some-dir"},"name": {"$match": "*"}}]},{"$and":[{"path": {"$match": "some-dir/*"},"name": {"$match": "*"}}]}]}).include("name","repo","path","actual_md5","actual_sha1","size","property","type")
```
Without `--include-dirs`
`jfrog rt set-props "some-repo/some-dir/" "a=1,b=2,3"`
```
[Debug] Searching Artifactory using AQL query:
 items.find({"repo": "some-repo","path": {"$ne": "."},"$or": [{"$and":[{"path": {"$match": "some-dir"},"name": {"$match": "*"}}]},{"$and":[{"path": {"$match": "some-dir/*"},"name": {"$match": "*"}}]}]}).include("name","repo","path","actual_md5","actual_sha1","size","property","type")
```

Should adding `--include-dirs` make a query where `"type": {"$eq": "folder"}` is included somewhere?

**Comment by romangurevitch** [comment]
@r631269,
Thank you for opening this issue, we committed a fix for the problem which will be included in our upcoming release.

**Comment by eyalbe4** [comment]
@r631269,
Version 1.12.0 has been released and includes the fix. Please let us know if it resolves the issue for you.

**Comment by r631269** [comment]
Yes, just tested 1.12.1, it appears to work now
