### ISSUE TITLE
Support multiple values in --deb as in set-props

### ISSUE THREAD

**Issue by mfriedenhagen** [JFrogDev/jfrog-cli-go#108]
Given I have create a GoLang based Debian package `foo_1.2.3_amd64.deb`
When I upload the artifact using `jfrog rt upload foo_1.2.3_amd64.deb deb-local/pool/foo/1.2.3/ --deb="jessie,wheezy,stretch/system/amd64`
Then I expect the artifact to be contained in all three distributions `jessie`, `wheezy` and `stretch`, i.e., appear in  all three `dists/DISTNAME/system/binary-amd64/Packages`.

However, this creates a new distribution called `jessie,wheezy,stretch`, i.e. in `dists/jessie,wheezy,stretch/system/binary-amd64/Packages`

This is inconsistent with `set-props` as well, where a `jfrog rt set-props deb-local/pool/foo/1.2.3/foo_1.2.3_amd64.deb "deb.distribution=jessie,wheezy,stretch;deb.component=system;deb.architecture=amd64"` does the IMHO correct thing to put the artifact in all three distributions.

I consider this is a bug.

BTW: Same bug in parsing of the `--props` flag: if I execute `jfrog rt upload foo_1.2.3_amd64.deb deb-local/pool/foo/1.2.3/ --props="deb.distribution=jessie,wheezy,stretch;deb.component=system;deb.architecture=amd64` I get this strange distribution again.

**Comment by romangurevitch** [comment]
@mfriedenhagen, 
Latest JFrog CLI version 1.13.1 was released and includes setting Debian multi value properties.
The syntax is similar to props flags comma separated values. 
We would appreciate your feedback on this.

**Comment by mfriedenhagen** [comment]
Hello, thanks, tested with two artifacts, seems to work.

**Comment by anlutro** [comment]
was there a regression here? doesn't seem to work using version 1.26.1:

```
$ docker run --rm -it docker.bintray.io/jfrog/jfrog-cli-go:latest jfrog rt upload --dry-run --deb xenial/example/all,bionic/example/all ./example.deb example-repo
[Error] The --deb option should be in the form of distribution/component/architecture
```

**Comment by mfriedenhagen** [comment]
You may not add several slash separated paths joined by a comma, but the parts between the slashes take commas as separator, e.g. wheezy,jessie/inhouse/amd64
