### ISSUE TITLE
github.com/gofrog/parallel vs github.com/jfrogdev/gofrog/parallel

### ISSUE THREAD

**Issue by maxlinc** [JFrogDev/jfrog-cli-go#109]
I see you've split out a client package.

When you try to get it with a tool like glide (i.e. `glide get github.com/jfrogdev/jfrog-cli-go/jfrog-client`) you run into an error fetching transitive dependencies because `github.com/gofrog/parallel` is actually at `github.com/jfrogdev/gofrog/parallel`.

**Comment by romangurevitch** [comment]
@maxlinc, thank you for reporting this issue.
We have pushed the following [commit](https://github.com/JFrogDev/jfrog-cli-go/commit/cc43304da1c54552373d6284a78dfc3b592f9d8c) fixing the import path in dev branch. 
The changes will be merges in our next upcoming release.

**Comment by eyalbe4** [comment]
@maxlinc,
@romangurevitch's commit made it to the master branch with the release of version 1.13.1.
Does this resolve the issue for you?

**Comment by eyalbe4** [comment]
@maxlinc,
I'm closing this issue for now. Please let us know if you need further help with this.
