### ISSUE TITLE
CLI and AWL spec support for offset

### ISSUE THREAD

**Issue by jgeorgeson** [JFrogDev/jfrog-cli-go#110]
Similar to #56 I would like to have AQL offset support. My use case is for writing cleanup scripts for repositories not using a package type and/or layout that supports automatic integration/snapshots build cleanup and want to delete all but the _N_ youngest builds.

Presently to cleanup by count I send a REST AQL query that uses sort and offset and then iterate over the JSON response.

```json
items.find(
    {
        "repo":{"$eq":"@@repo@@"},
        "$and": [
            {"path":{"$eq":"@@sitePath@@"}},
            {"type":{"$eq":"folder"}},
            {"name":{"$ne":"build"}},
            {"name":{"$nmatch":"*-Drop*"}},
            {"name":{"$nmatch":"*-alpha*"}},
            {"name":{"$nmatch":"*-beta*"}},
            {"name":{"$nmatch":"*-milestone*"}},
            {"name":{"$nmatch":"*-rc*"}},
            {"name":{"$nmatch":"*-final*"}},
            {"name":{"$nmatch":"*-sp*"}},
            {"name":{"$match":"*-*"}}
        ]
    }
).include("path","name","updated").sort({"$desc": ["updated"]}).offset(14)
```

I use `sed` to fill in the `@@repo@@` and `@@sitePath@@` before making the REST call.

Being able to do use this with a singular `jfrog rt delete --spec --spec-vars` command would be a very nice improvement.

**Comment by ortsi** [comment]
@jgeorgeson ,
Thanks for your input! we're actually already evaluating the effort for this task and we'll probably address this in one of the upcoming releases.

**Comment by romangurevitch** [comment]
@jgeorgeson,
We have pushed the following [commit](https://github.com/JFrogDev/jfrog-cli-go/commit/0900524b787edf497452214ee73357463d612221) which adds the offset option.
It will be available in our next release.

**Comment by eyalbe4** [comment]
@jgeorgeson,
@romangurevitch's code made it to version 1.13.1. 
It includes *offset* as a new command option and a File Spec property.

**Comment by eyalbe4** [comment]
@jgeorgeson,
With your permission, I'm closing this issue.
