### ISSUE TITLE
jfrog rt search JSON output is unusable without filtering

### ISSUE THREAD

**Issue by thiagofigueiro** [JFrogDev/jfrog-cli-go#115]
If you're trying to pipe the output of `jfrog rt search` to another command or to a JSON file, you need to filter it so the output is valid JSON.

E.g.:

```
$ jfrog rt search generic/doc* | jq .
[Info] Searching artifacts...
[Info] Found 28 artifacts.
[
  {
    "path": "generic/doc-something/1.8.0/foo.bar"
  },
  {
    "path": "generic/doc-pants/bar.tgz"
  },
  {
# (...)
parse error: Invalid numeric literal at line 1, column 6
$ echo $?
4
```

Work-around example:
```
$ jfrog rt search generic/doc* | grep -v '^\[Info' | jq .
# (...)
$ echo $?
0
```

As you can see, the `[Info]` lines at the top break the otherwise valid JSON output.

Fix suggestions:

1. Write the `[Info]` lines to stderr
2. Remove the `[Info]` lines altogether
3. Include an option to toggle the output of `[Info]` lines.

**Comment by eyalbe4** [comment]
@thiagofigueiro,
You can set the default log level to error by setting the value of the *JFROG_CLI_LOG_LEVEL* environment variable to *ERROR*. This way you can easily parse the command output with *jq*.

We're also considering adding an option for all commands, to print the log messages into a file, leaving only the commands JSON output redirected to the standard output.

**Comment by thiagofigueiro** [comment]
Thank you for the information.

I like the way curl does it. It prints information to stderr and the actual output to stdout. This makes it very straightforward to handle all the output and works by default in most situations. 

Feel free to close this if you have it tracked somewhere else. I did a quick search on github issues but didn’t see anything related. 

Sent on the run; please excuse my brevity.

**Comment by eyalbe4** [comment]
@thiagofigueiro,
Just wanted to let you know that we're currently implementing your suggestion. The CLI will print its log messages to the standard error, allowing you to parse the search command's output with tools like *jq*, without having to modify the log level.
Also, commands like upload and download which currently do have a JSON output, will output a JSON summary. 
We'll let you know when the code is committed.
Thanks you!

**Comment by romangurevitch** [comment]
@thiagofigueiro,
Latest JFrog CLI version 1.13.1 was released and includes new summary json output to the stdout.
All loggin information is printed to stderr.
We would appreciate your feedback on this.

**Comment by thiagofigueiro** [comment]
Thank you, @romangurevitch. We've upgraded our build pipeline today. I'll update here tomorrow.

**Comment by thiagofigueiro** [comment]
Confirmed working on 1.13.1

**Comment by salob** [comment]
I actually get this error and am using version 1.43.2 on mac. Was it re-introduced ?
