### ISSUE TITLE
upload --include-dirs option, upload all directories in a path

### ISSUE THREAD

**Issue by marekmrowca** [JFrogDev/jfrog-cli-go#117]
Hi,
is there a possibility to upload all directories in a path?
Command:
`jfrog rt u`
According to documentation https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory
--include-dirs uploads only botton-chain directories. How to upload all directories?

E.g.
I have a/b/c/file.zip and want to have the same structure on the server and not ony file.zip

Best regards,
Marek

**Comment by romangurevitch** [comment]
@marekmrowca, 
To preserve upload path add `--flat=false` flag to the upload command. 
By default this flag is set to true in upload command hence all your artifacts will be uploaded without preserving the original file path to the destination.
More information can be found [here ](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-UploadingFiles).

**Comment by marekmrowca** [comment]
It looks it works, thanks!
