### ISSUE TITLE
Split into go client library?

### ISSUE THREAD

**Issue by tartale** [JFrogDev/jfrog-cli-go#12]
Hi!  I was happy to find this tool and was able to use it in my project - how do you guys feel about splitting part of the project into a Go client library?  I could see some of the CLI options being useful as library calls, as well as some additional features (such as the List feature being discussed in issue #2)

Thanks!

**Comment by eyalbe4** [comment]
Hi @tartale,
You can already use jfrog-cli-go as a library and we would love to see it embedded in other applications. We made sure to keep the commands relate code separated from the CLI code, so that you can involve the commands from your go application, the same way the CLI code does. Look at the cli.go files. You'll notice that only they are CLI related. Your code can invoke the commands the same way.

**Comment by tartale** [comment]
Thanks for the quick reply!  I'm actually currently doing this, and found that, if you use the commands code as an entry point, it *mostly* works, with one exception - if the command you're calling experiences an error, the command doesn't return an error - it actually panics due to the assumption that the CLI library (codegansta) was initialized.

If you guys weren't interested in splitting the library out, another possibility would be to update to the latest of the codegansta/cli (moved to urfave/cli) allows the command function to return an error.

**Comment by eyalbe4** [comment]
Thanks for pointing out this issue @tartale. We'll modify the commands API so that all commands return an error instead of a panic. We'll let you know when done.

**Comment by eyalbe4** [comment]
@tartale, just updating that we've already started working on modifying code, so that all APIs return an error, rather than exiting, when the packages is used as a library.

**Comment by tartale** [comment]
@eyalbe4 Great to hear - thank you!

**Comment by eyalbe4** [comment]
@tartale, we pushed the code into the *dev* branch. It might still change a bit before the next release, but you can already look at it.

**Comment by eyalbe4** [comment]
@tartale, JFrog CLI 1.5.0 includes this change. It does not exit when used as a library.

**Comment by tartale** [comment]
@eyalbe4 Thank you!  I'll try it out

**Comment by eyalbe4** [comment]
@tartale, I'm closing this issue for now. When you get a chance to use the APIs, we'd appreciate your feedback.
