### ISSUE TITLE
Default credentials used for any host

### ISSUE THREAD

**Issue by Alexander-Haas** [JFrogDev/jfrog-cli-go#126]
When I got a config like this:

```
{
  "artifactory": [
    {
      "url": "https://a.net/artifactory/",
      "apiKey": "AKCp5Z[...]exqhkf",
      "serverId": "a.net",
      "isDefault": true
    }
  ],
  "Version": "1"
}
```

and I do this on the CLI:

```
$ jfrog rt s my-repo/my-tool* --url=https://b.net/artifactory
```

the CLI is accessing `b.net` using the credentials for `a.net` from the config file.

I consider this a security risk.

**Comment by yahavi** [comment]
@Alexander-Haas,
Thanks for reporting this issue.
Version 1.14.0 has been released and includes a fix for this.
We'll appreciate you feedback for that.

**Comment by Alexander-Haas** [comment]
Thank you for your swift action.
I tested it and found it resolved.
