### ISSUE TITLE
Provide CLI argument for setting CI Server URL when publishing build information

### ISSUE THREAD

**Issue by djhaskin987** [JFrogDev/jfrog-cli-go#127]
currently the CLI sets the CI Server URL to blank when it uploads build information into artifactory. Please make this value settable via an argument, so that I can use the CLI from e.g. Jenkins. This would be really nice. I *could* just use the jenkins plugin, but I have a bunch of variables set in my bash script that I want to use when I publish, and I can't bring them out of the shell script and into the groovy portion of my Jenkinsfile.

**Comment by eyalbe4** [comment]
@djhaskin987,
Version 1.14.0 has been released and includes a new *build-url* option for the *build-publish* command. You can use it to add the URL of your CI server build to the build-info, so that it can be viewed and accessed from the Artifactory UI.

**Comment by djhaskin987** [comment]
YAY
