### ISSUE TITLE
Add exclusion filter to build environment collection command build-collect-env

### ISSUE THREAD

**Issue by neechbear** [JFrogDev/jfrog-cli-go#128]
It is not uncommon for build and CI/CD systems to store secrets or sensitive information inside environment variables. As an example, GitLab CI makes explicit provision for this, (see https://docs.gitlab.com/ce/ci/variables/README.html#secret-variables).

It would incredibly useful to be able to provide an exclusion filter argument to the `build-collect-env` command (https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-BuildIntegration-CollectingEnvironmentVariables), so that sensitive data is not collected and permanently stored in the Artifactory build record.

For example:

```bash
jfrog rt build-collect-env \
  --exclude="my_secret_variable" \
  --exclude="another_sensitive_variable" \
  --exclude="secret_*" \
  "$CI_PROJECT_NAME" "$CI_PIPELINE_ID"
```

A current work around is to simply undefine the variable on the command line, but it would be nice to filter with a glob for multiple things.

```
my_secret_variable="" another_sensitive_variable="" secret_one="" secret_two="" secret_three=""  jfrog rt build-collect-env "$CI_PROJECT_NAME" "$CI_PIPELINE_ID"
```

**Comment by neechbear** [comment]
It looks like the Artifactory plugin for Jenkins provides some similar functionality already. https://www.jfrog.com/confluence/display/RTF/Working+With+Pipeline+Jobs+in+Jenkins

```
def buildInfo = Artifactory.newBuildInfo()
buildInfo.env.filter.addInclude("*a*")
buildInfo.env.filter.addExclude("DONT_COLLECT*")
```

It would be good to provide something similar in the `jfrog` command too.

**Comment by yahavi** [comment]
@neechbear,
The environment variables filtering comes in `build-publish` step and not in `build-collect-env` step.
This feature allows you to collect many build environments and filter them only once before publishing.
In our case, this should supply the requirements: 
`jfrog rt bp my-build-name 18 --env-exclude="my_secret_variable;another_sensitive_variable;secret_*"`

Please let me know if it helped you.

**Comment by neechbear** [comment]
AH! Fantastic. We did think it very odd that such a feature didn't already exist. We were just looking at the wrong command for the specific option then. (Our bad).

Maybe there should be a mention or reference to the filtering functionality of the `build-publish` command from the command line help of the `build-collect-env` command?

Many thanks for your assistance and clarification!

**Comment by yahavi** [comment]
@neechbear,
Thanks for your feedback!
I just added a hint to the `build-collect-env` command: https://github.com/JFrogDev/jfrog-cli-go/commit/825cb8b614aaf0a52de3468fef231de585e3c584
