### ISSUE TITLE
Uploading beyond filesize limit through cli

### ISSUE THREAD

**Issue by metaldart** [JFrogDev/jfrog-cli-go#13]
I was able to upload an ISO file of 1.4 GB when my file size limit was 100MB. Was wondering if this issue should be opened here

**Comment by eyalbe4** [comment]
Hi @metaldart,
Artifactory allows restricting the max file size only for uploads done through the UI. You can easily apply a max size restriction by configuring your Artifactory web server.

**Comment by eyalbe4** [comment]
@metaldart, with your permission, I'm closing this issue.
