### ISSUE TITLE
download files from list

### ISSUE THREAD

**Issue by leipert** [JFrogDev/jfrog-cli-go#14]
we have a usecase where we want to download multiple files from artifactory, that live in paths which are not easily expressible by wildcards. Therefore we want to specify a list of files that should be downloaded, so that we can use the parallel downloading capabilities of the jfrog client

E.g.:

``` bash
# the following entries in list.txt
npm/tweetnacl/-/tweetnacl-0.13.3.tgz
npm/ua-parser-js/-/ua-parser-js-0.7.10.tgz
npm/uc.micro/-/uc.micro-1.0.2.tgz
npm/underscore/-/underscore-1.8.3.tgz
npm/urijs/-/urijs-1.18.1.tgz
```

command which downloads all items listed in `list.txt`:

```
jfrog rt dl --from-list ./list.txt
```

**Comment by eyalbe4** [comment]
Thank you for sharing this use case @leipert.
We are planning to start supporting a spec file, which defines the uploads or downloads to and from Artifactory. To allow maximum flexibility, the spec may include more information than just the list of files to be downloaded.

**Comment by TamirHadad** [comment]
@leipert , 
JFrog CLI 1.5.0 includes the capability of using a spec file.
For more details about the spec option please refer to our [documentation](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-UsingFileSpecs).

**Comment by leipert** [comment]
That looks promising. I am going to close this issue 👍
