### ISSUE TITLE
Make `rt search` parsable

### ISSUE THREAD

**Issue by phemmer** [JFrogDev/jfrog-cli-go#15]
Currently the output of the `rt search` command outputs a header such as:

```
Pinging Artifactory...
Done pinging Artifactory.
Searching Artifactory using AQL query: items.find({"repo": "my-repo","$or": [{"$and": [{"path": {"$match":"*"},"name":{"$match":"*"}}]}]}).include("name","repo","path")
Artifactory response: 200 OK
```

This makes is difficult to feed the output into commands such as `jq`.

Please provide some way of excluding this header, such as:
1. A "quiet" flag to suppress the output
2. Output the message to STDERR instead of STDOUT
3. Don't output the message if STDOUT is not a TTY.

**Comment by eyalbe4** [comment]
Thank you for this important feedback @phemmer. We're working on a solution and will update soon.

**Comment by eyalbe4** [comment]
@phemmer, 
Following your feedback, we added to version 1.4.1 a new environment variable named *JFROG_CLI_LOG_LEVEL* which can be set to *ERROR*. When setting the value to *ERROR*, only the json output is logged, if no errors occur. When this variable is not set, the default log level is *INFO*. This environment variable applies to all CLI commands. 
.

**Comment by leipert** [comment]
an workaround we use at the moment is:
```
jfrog rt dl repository/*.html --dry-run | grep "Downloading" | rev | cut -d " " -f 1| rev
```

**Comment by eyalbe4** [comment]
@leipert,
It looks like you're parsing the output of the *rt download* command, which is okay.
I think that @phemmer was looking for a way to parse the output of the *rt search* command and since version 1.4.1 it can be done, by simply setting the JFROG_CLI_LOG_LEVEL environment variable can set to ERROR.

**Comment by leipert** [comment]
yes. i know. we are using the script from above in simple Makefiles.
So maybe support of a `jfrog rt ls` would be nice addition as well (or a parameter to return `jfrog rt search` as a flat file instead of a json 👍 )

**Comment by eyalbe4** [comment]
In the future, the *rt search* command will probably be enhanced to allow returning more than just the path of the files, so it might be better to keep the output format as flexible as possible. Using *jq* is a great way for manipulating the output. Thanks @leipert for sharing your *jq* command here:
https://github.com/JFrogDev/jfrog-cli-go/issues/2#issuecomment-237610642
