### ISSUE TITLE
Return only path property

### ISSUE THREAD

**Issue by mazzy89** [JFrogDev/jfrog-cli-go#151]
Why JFrog CLI returns only `path` property?

**Comment by eyalbe4** [comment]
@mazzy89,
You probably refer to the output of the *jfrog rt search* command.
We've recently merged [this](https://github.com/JFrogDev/jfrog-cli-go/pull/104) pull request, which adds the artifact properties to the command's response.

**Comment by mazzy89** [comment]
Yes I mean that. I see so it will be available in some next releases at the moment or just from building the master. Thank you @eyalbe4
