### ISSUE TITLE
Checksum not validated when downloading

### ISSUE THREAD

**Issue by mikepurvis** [JFrogDev/jfrog-cli-go#157]
We're distributing some large binary objects via jfrog and have had issues with users getting corrupted downloads, likely due to wifi or other network problems.

My expectation when trying out JFrog CLI is that it would access to the Artifactory-stored SHA hashes and confirm the download as being correct before exiting. However, we have still had issues with corrupted files, even when downloading with this tool, so clearly it is not doing sufficient additional validation.

**Comment by yahavi** [comment]
@mikepurvis,
Our new release, JFrog CLI v1.16.0, includes this feature. Feel free to upgrade.
We'll appreciate your feedback for it.
