### ISSUE TITLE
Post buildInfo from Jenkins with jfrog-cli

### ISSUE THREAD

**Issue by neonman63** [JFrogDev/jfrog-cli-go#16]
Hello. How i can post a buildInfo for deb-package from Jenkins build to Artifactory with jfrog-cli? Or its possibly only with hand-created json-file and post this file with curl to the server?

**Comment by eyalbe4** [comment]
Hi @neonman63,
One way to do this from Jenkins is by using the [Artifactory DSL for Pipeline scripts](https://wiki.jenkins-ci.org/display/JENKINS/Artifactory+-+Working+With+the+Pipeline+Jenkins+Plugin). The DSL allows you create and publish build info. You can also use the *Artifactory Generic Integration* from a Jenkins *Free Style Project*. In the future, JFrog CLI will also include build-info support.

**Comment by eyalbe4** [comment]
@neonman63, closing this case with your permission. Please let us if you require further assistance.
