### ISSUE TITLE
deb props in JFrog cli different from the API

### ISSUE THREAD

**Issue by cscetbon** [JFrogDev/jfrog-cli-go#161]
I can't use a component that has multiple levels like `toolx/3.11.2` cause the debprops format supports only `distribution/component/architecture` which is different from the api where I can use `deb.component=toolx/3.11.2`

https://github.com/JFrogDev/jfrog-cli-go/blob/master/jfrog-cli/artifactory/cli.go#L1435-L1437

I consider it as an inconsistency between the CLI and the API

**Comment by yahavi** [comment]
@cscetbon,
Thanks for reporting this issue.
We are working on a fix for the next CLI version v1.16.0.

**Comment by yahavi** [comment]
@cscetbon,
JFrog CLI v1.16.0 is released.
This version supports escaping of the `/` character in the `--deb` upload flag.
Please run with `--deb=distribution/toolx\/3.11.2/architecture`
We'll appreciate you feedback for that.

**Comment by eyalbe4** [comment]
@cscetbon,
We're closing this issue for now.
Please let us know if you need further assistance with this.

**Comment by cscetbon** [comment]
Yeah, thank you guys. I'll try it soon but didn't have time to do it. I'll reopen this issue if it does not work as expected.
