### ISSUE TITLE
complete path is always used for move and copy commands

### ISSUE THREAD

**Issue by peshay** [JFrogDev/jfrog-cli-go#163]
I want to move a directory and all it files to a different directory. In the Web-UI it works like I want it, I have the option `Move to a Custom Path` there. I don't have such an option in the CLI client and if I want to move `repo-name/a/b` to be in `repo-name/c/b` it will end up in `repo-name/c/a/b`

**Comment by eyalbe4** [comment]
@peshay,
This is definitely supported. See https://github.com/JFrogDev/jfrog-cli-go/issues/168 as a reference.

**Comment by peshay** [comment]
ah okay thanks! so you have to work with placeholder and --flat !
