### ISSUE TITLE
cli will not copy single artifact docker image without changing name

### ISSUE THREAD

**Issue by pkelleratwork** [JFrogDev/jfrog-cli-go#168]
cannot complete a simple copy from one repo to another, keeping the name the same. hopefully the example with explain better...

what i'm trying to do is move a docker image via cli from one repo to another keeping the original name - I do not want the name to be automatically changed to cibuild/0.0.21. I just want it named 0.0.21 after copying it. Shouldn't the cli cp it work like linux cp?

```
$ jfrog --version
jfrog version 1.15.1
```

**Source Repo**
```
apps
  cibuilds
    0.0.21
```

**Expected Target Repo**
``` 
apps
  channels
    0.0.21
```

**Run**
```
 $ jfrog rt cp apps/cibuilds/0.0.21 apps/channels/
```

**Actual Target Repo** - _i don't want the docker image renamed_
```
apps
  channels
    cibuilds/0.0.21
```

**Comment by eyalbe4** [comment]
@pkelleratwork,
The best way to control your target path is to use [Placeholders](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-UsingPlaceholders). In your case, the following command should work:
```
jfrog rt cp "apps/cibuilds/0.0.21/(*)" "apps/channels/{1}" --flat=true
```
 Please let us know if this helps.

**Comment by pkelleratwork** [comment]
@eyalbe4 
Success!!! 
That was very close to what I needed - your example and the linked page taught me about placeholders. I was able to get what i needed with
`jfrog rt cp "apps/cibuilds/0.0.21/(*)" "apps/channels/0.0.21/{1}" --flat=true`

Thank you very much for your quick reply!!

**Comment by franleplant** [comment]
Hi Jfrog team! Thanks a lot for this tool.

I just wanted to share my experience with this which is that the default behavior is very counter-intuitive and I wonder why that is the way it is. Maybe we can add a warning or a note in the docs stating that in order to cover this seemingly very simple use case you need to specify `flat=true`.

What do you think?
