### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by gc-keba** [JFrogDev/jfrog-cli-go#17]
Hello,

i got this error when i download a folder:

Pinging Artifactory...
Done pinging Artifactory.
Searching Artifactory using AQL query: items.find({"repo": "gc-components","$or": [{"$and": [{"path": {"$match":"BrandResources/1.0.0.0/Keba"},"name":{"$match":"*"}}]},{"$and": [{"path": {"$match":"BrandResources/1.0.0.0/Keba/*"},"name":{"$match":"*"}}]}]}).include("name","repo","path","actual_md5","actual_sha1","size")
Artifactory response: 403 Forbidden
panic: invalid character 'O' looking for beginning of value
goroutine 1 [running]:
panic(0x87fb80, 0xc0820c2a40)
        /var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/g
o-1.6.2/src/runtime/panic.go:481 +0x3f4
github.com/jfrogdev/jfrog-cli-go/utils/cliutils.CheckError(0x3a5c18, 0xc0820c2a4
0)
        /var/lib/jenkins/workspace/jfrog-cli-release/temp/src/github.com/jfrogde
v/jfrog-cli-go/utils/cliutils/utils.go:28 +0x52
github.com/jfrogdev/jfrog-cli-go/artifactory/utils.parseAqlSearchResponse(0xc082
136000, 0x3b, 0x600, 0x0, 0x0, 0x0)
        /var/lib/jenkins/workspace/jfrog-cli-release/temp/src/github.com/jfrogde
v/jfrog-cli-go/artifactory/utils/aqlsearchutil.go:45 +0xb1
github.com/jfrogdev/jfrog-cli-go/artifactory/utils.AqlSearch(0xc082054000, 0x2b,
 0x31300b0, 0xc082011080, 0xc082073d70, 0x6, 0x6, 0x0, 0x0, 0x0)
        /var/lib/jenkins/workspace/jfrog-cli-release/temp/src/github.com/jfrogde
v/jfrog-cli-go/artifactory/utils/aqlsearchutil.go:39 +0x712
github.com/jfrogdev/jfrog-cli-go/artifactory/utils.AqlSearchDefaultReturnFields(
0xc082054000, 0x2b, 0x31300b0, 0xc082011080, 0x0, 0x0, 0x0)
        /var/lib/jenkins/workspace/jfrog-cli-release/temp/src/github.com/jfrogde
v/jfrog-cli-go/artifactory/utils/aqlsearchutil.go:26 +0xc5
github.com/jfrogdev/jfrog-cli-go/artifactory/commands.Download(0xc082054000, 0x2
b, 0xc082011080)
        /var/lib/jenkins/workspace/jfrog-cli-release/temp/src/github.com/jfrogde
v/jfrog-cli-go/artifactory/commands/download.go:24 +0x146
github.com/jfrogdev/jfrog-cli-go/artifactory.downloadCmd(0xc0820388c0)
        /var/lib/jenkins/workspace/jfrog-cli-release/temp/src/github.com/jfrogde
v/jfrog-cli-go/artifactory/cli.go:352 +0x2f8
github.com/jfrogdev/jfrog-cli-go/artifactory.GetCommands.func3(0xc0820388c0)
        /var/lib/jenkins/workspace/jfrog-cli-release/temp/src/github.com/jfrogde
v/jfrog-cli-go/artifactory/cli.go:40 +0x28
github.com/jfrogdev/jfrog-cli-go/vendor/github.com/codegangsta/cli.Command.Run(0
x9447d0, 0x8, 0x0, 0x0, 0xc082002f50, 0x1, 0x1, 0x93da50, 0xe, 0x0, ...)
        /var/lib/jenkins/workspace/jfrog-cli-release/temp/src/github.com/jfrogde
v/jfrog-cli-go/vendor/github.com/codegangsta/cli/command.go:174 +0x13a0
github.com/jfrogdev/jfrog-cli-go/vendor/github.com/codegangsta/cli.(*App).RunAsS
ubcommand(0xc082038640, 0xc082038500, 0x0, 0x0)
        /var/lib/jenkins/workspace/jfrog-cli-release/temp/src/github.com/jfrogde
v/jfrog-cli-go/vendor/github.com/codegangsta/cli/app.go:298 +0x11d0
github.com/jfrogdev/jfrog-cli-go/vendor/github.com/codegangsta/cli.Command.start
App(0x939520, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x982cc0, 0x14, 0x0, ...)
        /var/lib/jenkins/workspace/jfrog-cli-release/temp/src/github.com/jfrogde
v/jfrog-cli-go/vendor/github.com/codegangsta/cli/command.go:249 +0x756
github.com/jfrogdev/jfrog-cli-go/vendor/github.com/codegangsta/cli.Command.Run(0
x939520, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x982cc0, 0x14, 0x0, ...)
        /var/lib/jenkins/workspace/jfrog-cli-release/temp/src/github.com/jfrogde
v/jfrog-cli-go/vendor/github.com/codegangsta/cli/command.go:65 +0x80
github.com/jfrogdev/jfrog-cli-go/vendor/github.com/codegangsta/cli.(*App).Run(0x
c0820383c0, 0xc082006300, 0x6, 0x6, 0x0, 0x0)
        /var/lib/jenkins/workspace/jfrog-cli-release/temp/src/github.com/jfrogde
v/jfrog-cli-go/vendor/github.com/codegangsta/cli/app.go:187 +0x1132
main.main()
        /var/lib/jenkins/workspace/jfrog-cli-release/temp/src/github.com/jfrogde
v/jfrog-cli-go/jfrog/main.go:19 +0x112

the command:
jfrog.exe rt dl --url "http://lnzpc0663:8081/artifactory/" "gc-components/BrandResources/1.0.0.0/Keba/*"

**Comment by TamirHadad** [comment]
Hi,
Thanks for reporting this issue.
We are looking into it.

**Comment by TamirHadad** [comment]
Hi  @gc-keba, 
It look like you are running the download command without a user configured.
When downloading with wildcard, the command is executing an Aql search.
The Aql feature requires a user otherwise it returns 403 Forbidden response, even if an anonymous access is allowed in Artifactory .
In order to successfully download your artifact you should configure username and password.

For example : 
jfrog.exe rt dl  "gc-components/BrandResources/1.0.0.0/Keba/*" --url= http://lnzpc0663:8081/artifactory/ --user=username --password=password

**Comment by gc-keba** [comment]
Hi TamirHadad,
thank you for your responce. 
It tested it with username and password -> it works!
Now i have a problem with the created folders. The jfrog.exe creates the folders after "gc-components"! But i want the folder hierachy after "../Keba/". The option flat and recursive are not helping either.
How can i do that?

**Comment by romangurevitch** [comment]
Hi @gc-keba,
We are correctly working on improving the download flow by adding the ability to add target path which will also support replaceable destination path.
For example: 
`./jfrog rt dl Repo/relativePath/(path/to/file.txt) targetPath/{1} --flat=true`
The file will be downloaded to:
` targetPath/path/to/file.txt`

Currently the CLI supports only downloads to the current directory in flat/non-flat mode.
In non-flat mode, full path will be created.

**Comment by TamirHadad** [comment]
Hi @gc-keba,
From version 1.5 the download command supports downloads using a spec file.
The download file spec schema contains target which can be used in order to change the download path.
For more details about the spec option please refer to our [documentation](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory).

**Comment by eyalbe4** [comment]
@gc-keba, in addition to the spec file option mentioned by @TamirHadad, with 1.5.0 the *rt download* command also accepts a second optional argument, that defines the download path on the local file-system,  similar to @romangurevitch description above.

**Comment by eyalbe4** [comment]
@gc-keba, please let us know if you had a chance to try out the new features introduced in version 1.5.0 and described in this issue. We would appreciate your feedback. I'm closing this issue for now.
