### ISSUE TITLE
Issue with Artifactory's CLI upload command and wildcards

### ISSUE THREAD

**Issue by ndifolco** [JFrogDev/jfrog-cli-go#171]
Hi,

I'm trying to upload all the files from a "local/" directory to a "repo-name/a/b/" repository using wildcards.

My issue is that the following command uploads the directory "local" itself to "repo-name/a/b/":
**jfrog rt u "local/*" repo-name/a/b/**

So we end up having all the files in "repo-name/a/b/local/" instead of having them in "repo-name/a/b/".

Is this the expected behavior?

I was expecting to have the same behaviour than the UNIX "cp" command:
**cp -r local/\* repo-name/a/b/**

PS: I am using jfrog version 1.16.0.

**Comment by eyalbe4** [comment]
@ndifolco,
I think you can use https://github.com/JFrogDev/jfrog-cli-go/issues/163 as a reference for achieving this.
Please let us know if you need further help with this.

**Comment by ndifolco** [comment]
Thank you @eyalbe4 !

I was able to get it working finally.
The #163 issue refers to #168 issue which gives more details for resolution.

To get it working, I had to use the [Placeholder](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-UsingPlaceholders) feature, which is very powerful.

So the correct command looks like:
**jfrog rt u --include-dirs=true --flat=false "local/(*)" repo-name/a/b/{1}**

Thus I'm closing this issue.
