### ISSUE TITLE
download folder from artifactory keeping subfolder organisation

### ISSUE THREAD

**Issue by gsemet** [JFrogDev/jfrog-cli-go#176]
Hello.

I do not find a way to download a folder from artifactory to a local folder, keep all underneath hierarchy?

Let's say I have uploaded `reponame/path/to/my/project/` that has sub-folders `subfold1` and `subfold2`.

I would like to use jfrog cli to download `reponame/path/to/my/project/` and see on my destination folder directy the two forementioned subfolders `subfold1` and `subfold2`. Instead I got a folder `path/to/my/project/` where my subfolders are.

`--flat` does not preserve the subfolders.

For the moment, my solution is to keep download to the local reponame/path/to/my/project/` to a temporary folder, and then move the content of `reponame/path/to/my/project/*` to my destination folder, so something like:

```
jfrog.linux rt download --include-dirs=true --recursive 'reponame/path/to/my/project/*' tmpname
mv tmpname/reponame/path/to/my/project/* .
rm -rf tmpname
```

Thanks for your help

**Comment by eyalbe4** [comment]
@gsemet,
The best way to achieve this is by using [Place Holders](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-UsingPlaceholders).
You can also look at https://github.com/JFrogDev/jfrog-cli-go/issues/168 as an additional reference. 
Please let us know if you need further assistance with creating your download command.

**Comment by gsemet** [comment]
Hi. In the docs it is stated that the placeholders only work for upload ("The JFrog CLI offers enormous flexibility in how you upload, copy, or move files through use of wildcard or regular expressions with placeholders in the upload command.").

Does it also works for download?

**Comment by eyalbe4** [comment]
Correct @gsemet.
We'll fix the documentation.

**Comment by gsemet** [comment]
Tested. It does not do what I expect:
```
jfrog.linux rt download --include-dirs=true --recursive 'reponame/path/to/my/project/(*)' '{1}/'
```
Actually creates a **folder** on the root with the same directory structure:
```
file1/reponame/path/to/my/project/file1
file2/reponame/path/to/my/project/file2
```

while I want just `file1` and `file2` (+ all subfolder if any) at the very root :(

**Comment by gsemet** [comment]
I do not want to flatten the download structure, what if there are subdiretories ?

I also do not see which use case the placeholders behavior for download is for? I simply would like to get the local structure like if i have downloaded a zip file with —expand.

I can open a new ticket to track the weird behavior of the download.
I think this should be fixed, as it provides the mirror operation of « upload »

**Comment by eyalbe4** [comment]
@gsemet,
Adding --flat=true should maintain the structure in your case.
Are you saying that the above command with **--flat=true** get you a result different from the following?
```
dir1/reponame/path/to/my/project/dir1/file1
dir1/reponame/path/to/my/project/dir1/file2
```

**Comment by gsemet** [comment]
I will try it tomorow.

I find weird to get this structure be recreated.

I would expect to get this behavior for something like:
```
$ jfrog rt download --include-dirs=true --recursive '(reponame/path/to/my/project/*)' '{1}'
=> 
reponame/path/to/my/project/dir1/file1
reponame/path/to/my/project/dir1/file2
```

I'll see tomorow if this works:
```
$ jfrog rt download --include-dirs=true --flat=true --recursive 'reponame/path/to/my/project/(*)' '{1}'
=> 
dir1/file1
dir1/file2
```

What I want is precisely:
`reponame/path/to/my/project/dir1/file1` => `./dir1/file1`
`reponame/path/to/my/project/dir1/file2` => `./dir1/file2`
`reponame/path/to/my/project/dir1/subdir1/file1` => `./dir1/subdir1/file1`

**Comment by gsemet** [comment]
Hello

I confirm that the following syntax gives the indented result:
```
$ jfrog rt download --include-dirs=true --flat=true --recursive 'reponame/path/to/my/project/(*)' '{1}'
...
$ find .
./dir1/file1
./dir1/file2
./dir1/subdir1/file1
./dir1/subdir1/file2
```

**Comment by TANguyen1893** [comment]
I would like to know if the behaviour is different based on the artifactory version. On artifactory version 5.8.4 the correct behaviour is observed, however on artifactory version 6.3.3, the behaviour is not respected. On 6.3.3, all files are downloaded and saved on the local filesystem with filename {1} with the following command 
` jfrog rt download --include-dirs=true --flat=true --recursive 'reponame/path/to/my/project/(*)' '{1}'`

**Comment by jmwolfe** [comment]
On Artifactory 1.16.1, when  I use the above, first off I have to use double quotes, not single. Single quotes return zero files.

Second, it seems to be creating an empty directory. IE in artifactory:

a/b/c.txt
a/b/d.txt

when i download it

`jfrog rt download --include-dirs=true --flat=true --recursive "reponame/a/(*)" "{1}" I get:`

```./b/c.txt
./b/d.txt
./b/b (directory)
```

same happens if I use:

`jfrog rt download --include-dirs=true --flat=true --recursive "reponame/a/(b/*)" "b/{1}"`

**Comment by lookilooki** [comment]
How are the settings, if I'm using a spec file? 

I have a spec file within I defined some files to download and like to store in a folder structure I give.

Thanks for info
