### ISSUE TITLE
wrong property conversion

### ISSUE THREAD

**Issue by hknochi** [JFrogDev/jfrog-cli-go#18]
Hey, 

thanks for this great client. but i'Ve some problems while uploading svg images

```
jfrog rt upload --flat=false --props "artifactory.content-type=image/svg+xml" "images/*.svg" $DESTINATION_REPO
```

but these resources will have the wrong value: "image/svg xml" for the key: "artifactory.content-type"

i've tried to encode or escape the "+" character  --> but without any success.

**Comment by TamirHadad** [comment]
Hi,
Thanks for reporting this issue.
We are working on a fix.

**Comment by TamirHadad** [comment]
Hi @hknochi,
Our latest release contains a fix for encoding properties with special characters.
Can we close the issue?

**Comment by eyalbe4** [comment]
@hknochi, I'm closing this issue. Please let us know in case version 1.5.0 does not resolve the issue for you.

**Comment by hknochi** [comment]
@TamirHadad: Sorry for my late response. i was on vacation. 

I've tested v1.5.0 and it seem to be fixed :-D 

Thanks a lot for this great work
