### ISSUE TITLE
Add list and delete cli command options

### ISSUE THREAD

**Issue by jsabo** [JFrogDev/jfrog-cli-go#2]
Having the ability to list repositories and packages would be a big help, as would having the ability to delete packages.  I'd like to request this as an enhancement.

**Comment by eyalbe4** [comment]
The option to delete packages already exists using the *package-delete* command. We'll look into the other two requests. Thanks @jsabo.

**Comment by tmds** [comment]
I am looking at the jfrog cli documentation: https://www.jfrog.com/confluence/display/RTF/JFrog+CLI.
There doesn't seem to be a command to delete an artifact?

**Comment by romangurevitch** [comment]
Delete, move and copy artifacts commands will be added in our next release.
The commands are already commited to `dev ` branch, you are welcome to clone, build and use it. 
Thanks @tmds.

**Comment by romangurevitch** [comment]
@tmds, version 1.2.0 has been released and includes move, copy and delete commands.

**Comment by tmds** [comment]
@romangurevitch super!

**Comment by jonathan-luminal** [comment]
looking forward to 1.2.0 showing up in homebrew

**Comment by eyalbe4** [comment]
Sure @jonathan-luminal. We submitted the pull request for 1.2.0 to homebrew today.

**Comment by jonathan-luminal** [comment]
Can you use any of the following to get a listing of what's in artifactory or bintray?

```
$ jfrog --version
jfrog version 1.2.0
$ jfrog rt --help
NAME:
   jfrog rt - Artifactory commands

USAGE:
   jfrog rt command [command options] [arguments...]

COMMANDS:
   config, c	Configure Artifactory details
   upload, u	Upload files
   download, dl	Download files
   move, mv	Move files
   copy, cp	Copy files
   delete, del	Delete files
   help, h	Shows a list of commands or help for one command

OPTIONS:
   --help, -h	show help
```

**Comment by eyalbe4** [comment]
Hi @jonathan-luminal,
Yes, you can use:
```console
jfrog rt
```
to see the list of available Artifactory commands and  
```console
jfrog bt
```
for the Bintray commands.
It recommended to use the online documentation for details about the commands arguments.

**Comment by tmds** [comment]
@eyalbe4 @jonathan-luminal is asking for a command to list artifacts, which would be very useful.

The output of this command could be lines in the form [repository_name]/[repository_path]. For example, you can then take the output, pipe it to grep and then use it as input for the delete command.
A --recurse can allow you to list recursively.

For efficiency reasons it may be handy to support providing a filter as part of the list command if the server supports such a list query.

**Comment by eyalbe4** [comment]
Got it @tmds. Thanks.
We are planning to support list (search) of artifacts in future releases.

**Comment by eyalbe4** [comment]
@jonathan-luminal, version 1.2.0 of jfrog-cli-go is available in homebrew.

**Comment by eyalbe4** [comment]
@jonathan-luminal and @tmds, version 1.4.0 of the CLI adds a new *search* command for Artifactory.

**Comment by leipert** [comment]
if you want a plain list, you could just use [jq](https://stedolan.github.io/jq/):
```
JFROG_CLI_LOG_LEVEL=ERROR jfrog rt search repository/*.html | jq .[].path --raw-output
```

**Comment by eyalbe4** [comment]
The JFROG_CLI_LOG_LEVEL environment variable was added in version 1.4.1. it will be soon available in homebrew as well. Closing this issue.

**Comment by varunmsv1992** [comment]
Hello, trying to delete artifacts using JFrog CLI according to build.number property. Using the following command to delete single artifact   jfrog rt del repo/path  --props=build.number=50.   I want to delete artifacts having build number 50-75. Can any one please help me?

**Comment by markgalpin** [comment]
In general this is not a forum that can be used for questions like this.  That said, in order to do this you will have to use AQL in a filespec with the CLI:
https://www.jfrog.com/confluence/display/RTF/Using+File+Specs#UsingFileSpecs-DownloadSpecSchema

For additional questions, if you have a support package please contact JFrog Support.

**Comment by eyalbe4** [comment]
@varunmsv1992 and @markgalpin,
JFrog CLI indeed supports AQL queries by using File Specs, but [this](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-UsingFileSpecs) is the correct link to the File Specs documentation specific for JFrog CLI.
@varunmsv1992, the *delete* command includes the *build* option, which allows specifying a build name and number. The command however does not currently support providing a range of builds. We are considering to add a new *build retention* command in the future.
