### ISSUE TITLE
Downloading files with empty content

### ISSUE THREAD

**Issue by Aravindpogu** [JFrogDev/jfrog-cli-go#20]
When I try to download file from artifactory using the following comamnd:

`$ ./jfrog rt dl path/to/file/myfile.zip `

I got the response like 

Pinging Artifactory...
Done pinging Artifactory.
[Thread 0] : Artifactory response: 200 OK

But, the file is empty.

`$ du -h path/to/file/myfile.zip `
0 path/to/file/myfile.zip 

And, I'm sure myfile.zip in the artifactory is not empty.

**Comment by eyalbe4** [comment]
@Aravindpogu,
How can we reproduce this issue? For troubleshooting purposes, can you please try downloading the file through Artifactory's UI or using a different client like curl? Artifactory did return 200 OK for the download request and this a very basic usage of the CLI, so we could really use some more information and troubleshooting attempts you can make. Thank you.

**Comment by apogu** [comment]
@eyalbe4 Never mind. I've provided a wrong url and artifactory location. That caused the problem.

**Comment by eyalbe4** [comment]
Thanks @apogu. Closing this issue.
