### ISSUE TITLE
--props doesn't search correctly

### ISSUE THREAD

**Issue by spuder** [JFrogDev/jfrog-cli-go#26]
When I try and use --props to filer which artifacts I want to delete, it generates an invalid search. 

```bash
jfrog rt del foobar --props "size=781717698"  --dry-run
```

This generates a search, which returns no results

```json
items.find({
  "repo": "foobar",
  "@size": {
    "$match": "781717698"
  },
  "$or": [{
    "$and": [{
      "path": {
        "$match": "*"
      },
      "name": {
        "$match": "*"
      }
    }]
  }]
}).include("name", "repo", "path", "actual_md5", "actual_sha1", "size")

```

The search that I expect to be run:

```json
items.find(
  {
      "repo":"foobar",
      "size": "781717698"
  }
)
```

Is this a bug in the way --props works? or am I misinterpreting the documentation? 

https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-DeletingFiles

**Comment by spuder** [comment]
I think I've figured this out. It seems --props is only for searching for 'tags'. 

An AQL search is done with --spec

http://stackoverflow.com/questions/40118550/artifactory-delete-all-artifacts-older-than-6-months/40118551#40118551

It would be nice if the documentation clarified what --props is for.

**Comment by eyalbe4** [comment]
Thanks for pointing that out @spuder.
We will soon update the documentation, so that it is clear that --props refers to [properties](https://www.jfrog.com/confluence/display/RTF/Properties).

**Comment by eyalbe4** [comment]
@spuder, we updated the --props description in the documentation, and [properties](https://www.jfrog.com/confluence/display/RTF/Properties) is now a link. With your permission, I'm closing this issue.

**Comment by jbruns2015** [comment]
Got any examples of how to do a search and say only show files modified today?

jfrog rt s "<myurl>" --props modified=<something>

?

**Comment by markgalpin** [comment]
As noted, props is only for extensible properties.  modified is a more complex AQL query, see the docs for AQL in the spec
