### ISSUE TITLE
capabilities to add symlinks to Artifactory

### ISSUE THREAD

**Issue by jainishshah17** [JFrogDev/jfrog-cli-go#27]
when try to upload a file to Artifactory using JFrog CLI ```jfrog rt u --flat=false  "*" repo``` it should recognize if a file is a symlink having flag enabled for example ```jfrog rt u --flat=false --symlink=true  "*" repo```. In a case of symlink it should create an artifact with size 0 in Artifactory and add property `symlink` with a value of destination to symlink. It should do same when we are a downloading file from Artifactory using CLI.  Check if artifact has property `symlink` then create symlink in destination directory.

**Comment by eyalbe4** [comment]
JFrog CLI 1.7.0 has been released and includes the functionality of storing symlinks in Artifactory.
Read more about this feature in the "Storing Symlinks in Artifactory" section in the [JFrog CLI for Artifactory User Guide](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory).

**Comment by sks** [comment]
@eyalbe4 

Are there any Docs that I can read on how to use file upload specs to add symlinks to a artifactory path ?
