### ISSUE TITLE
Please add support for reporting error messages from the server

### ISSUE THREAD

**Issue by NicolasRouquette** [JFrogDev/jfrog-cli-go#28]
Troubleshooting problems pertaining to publishing to artifactory can be tedious if one does not have admin access to look at the artifactory system logs.

It would be helpful if the CLI provided an option, e.g., `--debug`, to include in the output whatever error information comes from the server in such cases.

**Comment by eyalbe4** [comment]
Thanks for reporting this @NicolasRouquette.
We'll work on adding the response message text returned from Artifactory for all commands.

**Comment by NicolasRouquette** [comment]
@eyalbe4 That will be excellent!

**Comment by romangurevitch** [comment]
@NicolasRouquette, in our latest release we have improved the logging output and added more log levels. 
Choosing log level is done by setting the following environment variable: JFROG_CLI_LOG_LEVEL.
Available log levels are: DEBUG, INFO, WARN, ERROR.
In debug mode all responses are logged and displayed.
Please let us know if you need more logging information.

**Comment by eyalbe4** [comment]
@NicolasRouquette, the latest CLI releases log all the response text returned by the Artifactory REST APIs. In case you encounter a case where additional info should be logged, please let us know.
I'm closing this issue for now.
