### ISSUE TITLE
jfrog bt logs points to the wrong docs

### ISSUE THREAD

**Issue by areese** [JFrogDev/jfrog-cli-go#29]
Running jfrog bt logs sends you to the git repo README.md, which tells you how to build the CLI.

```
./jfrog bt logs 
[Error:] Wrong number of arguments. You can read the documentation at https://github.com/jfrogdev/jfrog-cli-go/blob/master/README.md
```

It probably should send you here:
https://www.jfrog.com/confluence/display/CLI/Welcome+to+JFrog+CLI

Or since it was jfrog bt I was passing the wrong information to:
https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Bintray

**Comment by eyalbe4** [comment]
Thanks @areese. We'll fix this in the next release.

**Comment by romangurevitch** [comment]
@areese, 
In our latest release (1.10.1) we made many documentation improvements. 
You are welcome to try it out using `--help` flag.
For example: `jfrog bt logs --help`

**Comment by areese** [comment]
Looks much better thanks.
