### ISSUE TITLE
https with self signed cert

### ISSUE THREAD

**Issue by maurorappa** [JFrogDev/jfrog-cli-go#3]
Hi,
if I specify an https url which uses a self signed certificate, the utility crashes badly :)

./jfrog rt u apache-tomcat-8.0.32-5.noarch.rpm hass_rpms --user=mauro --password=xxxxxx --url=https://libraries.dev2.cloud.local/artifactory/
[Thread 0] Uploading artifact: https://libraries.dev2.cloud.local/artifactory/hass_rpms/apache-tomcat-8.0.32-5.noarch.rpm
panic: Put https://libraries.dev2.cloud.local/artifactory/hass_rpms/apache-tomcat-8.0.32-5.noarch.rpm: x509: certificate signed by unknown authority

goroutine 5 [running]:
github.com/jfrogdev/jfrog-cli-go/cliutils.CheckError(0x7fa8be161428, 0xc82042a810)
	/home/travis/gopath/src/github.com/JFrogDev/jfrog-cli-go/Godeps/_workspace/src/github.com/jfrogdev/jfrog-cli-go/cliutils/utils.go:26 +0x4b
github.com/jfrogdev/jfrog-cli-go/cliutils.Send(0x8860d0, 0x3, 0xc82001c360, 0x5a, 0x0, 0x0, 0x0, 0xc82004bc70, 0xc82003bd01, 0xc820013500, ...)
	/home/travis/gopath/src/github.com/JFrogDev/jfrog-cli-go/Godeps/_workspace/src/github.com/jfrogdev/jfrog-cli-go/cliutils/ioutils.go:167 +0x4f9
github.com/jfrogdev/jfrog-cli-go/cliutils.SendPut(0xc82001c360, 0x5a, 0x0, 0x0, 0x0, 0xc82004bc70, 0xc820013500, 0xa, 0xc820013520, 0xa, ...)
	/home/travis/gopath/src/github.com/JFrogDev/jfrog-cli-go/Godeps/_workspace/src/github.com/jfrogdev/jfrog-cli-go/cliutils/ioutils.go:129 +0xd9
github.com/jfrogdev/jfrog-cli-go/artifactory/commands.tryChecksumDeploy(0x7ffd4535f68a, 0x21, 0xc82001c360, 0x5a, 0xc82001c180, 0x0, 0x5a)
	/home/travis/gopath/src/github.com/JFrogDev/jfrog-cli-go/Godeps/_workspace/src/github.com/jfrogdev/jfrog-cli-go/artifactory/commands/upload.go:167 +0x2bf
github.com/jfrogdev/jfrog-cli-go/artifactory/commands.uploadFile(0x7ffd4535f68a, 0x21, 0xc82001c360, 0x5a, 0xc82001c180, 0xc820013630, 0xa, 0x0)
	/home/travis/gopath/src/github.com/JFrogDev/jfrog-cli-go/Godeps/_workspace/src/github.com/jfrogdev/jfrog-cli-go/artifactory/commands/upload.go:137 +0x3fd
github.com/jfrogdev/jfrog-cli-go/artifactory/commands.Upload.func1(0xc82001c180, 0x1, 0xc820011380, 0x1, 0x1, 0xc8200113a0, 0x3, 0x3, 0xc8200135f0, 0x0)
	/home/travis/gopath/src/github.com/JFrogDev/jfrog-cli-go/Godeps/_workspace/src/github.com/jfrogdev/jfrog-cli-go/artifactory/commands/upload.go:38 +0x13d
created by github.com/jfrogdev/jfrog-cli-go/artifactory/commands.Upload
	/home/travis/gopath/src/github.com/JFrogDev/jfrog-cli-go/Godeps/_workspace/src/github.com/jfrogdev/jfrog-cli-go/artifactory/commands/upload.go:43 +0x1e3

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc8200135fc)
	/usr/local/go/src/runtime/sema.go:43 +0x26
sync.(*WaitGroup).Wait(0xc8200135f0)
	/usr/local/go/src/sync/waitgroup.go:126 +0xb4
github.com/jfrogdev/jfrog-cli-go/artifactory/commands.Upload(0x7ffd4535f68a, 0x21, 0x7ffd4535f6ac, 0x9, 0xc82001c180, 0xc820061a00, 0xc8200133f0)
	/home/travis/gopath/src/github.com/JFrogDev/jfrog-cli-go/Godeps/_workspace/src/github.com/jfrogdev/jfrog-cli-go/artifactory/commands/upload.go:45 +0x1fe
github.com/jfrogdev/jfrog-cli-go/artifactory.upload(0xc8200903c0)
	/home/travis/gopath/src/github.com/JFrogDev/jfrog-cli-go/Godeps/_workspace/src/github.com/jfrogdev/jfrog-cli-go/artifactory/cli.go:253 +0x2a1
github.com/jfrogdev/jfrog-cli-go/artifactory.GetCommands.func2(0xc8200903c0)
	/home/travis/gopath/src/github.com/JFrogDev/jfrog-cli-go/Godeps/_workspace/src/github.com/jfrogdev/jfrog-cli-go/artifactory/cli.go:32 +0x21
github.com/JFrogDev/jfrog-cli-go/Godeps/_workspace/src/github.com/codegangsta/cli.Command.Run(0x8897d8, 0x6, 0x0, 0x0, 0xc820012de0, 0x1, 0x1, 0x88f520, 0xc, 0x0, ...)
	/home/travis/gopath/src/github.com/JFrogDev/jfrog-cli-go/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:174 +0x1397
github.com/JFrogDev/jfrog-cli-go/Godeps/_workspace/src/github.com/codegangsta/cli.(*App).Run(0xc820090140, 0xc82000a090, 0x7, 0x7, 0x0, 0x0)
	/home/travis/gopath/src/github.com/JFrogDev/jfrog-cli-go/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:187 +0x1135
main.main()
	/home/travis/gopath/src/github.com/JFrogDev/jfrog-cli-go/jfrog/main.go:24 +0x315

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

can we put an option to ignore its verification like curl o wget have ?

Thanks

**Comment by TamirHadad** [comment]
Actually we have started working on this issue few days ago.
This issue will be resolved in the next cli version, 1.1.0.
The fix is already part of branch 1.1.0, if you want you can take a look at the <a href =https://github.com/JFrogDev/jfrog-cli-go/commit/e11ca2b3f58d650c5759544a3fb0abb8aacaf343> commit </a>.

**Comment by maurorappa** [comment]
Cool, if you could build it, I'm new to go..

**Comment by TamirHadad** [comment]
Hi @maurorappa , 
A new version of <a href = https://www.jfrog.com/getcli/ >JFrog CLI</a> was released.
In addition to a few enhancements and improvements it includes support for <a href = https://www.jfrog.com/confluence/display/RTF/JFrog+CLI#JFrogCLI-UsingSelf-signedSSLCertificates> self-signed certificates Artifactory </a>.

**Comment by maurorappa** [comment]
I'm very sorry Tamir, I didn't specify enough my problem.
The self signed certificate is the certificate on the server side;  not the one used for the client authentication. In my example you can see I use basic authentication but I target an https url (an nginx reverse proxy in front of Artifactory, a _very_ common setup).

I tried jfrog 1.1 and it crashes:

$ ./jfrog rt u ~/apache-tomcat-8.0.32-5.noarch.rpm hass_rpms --user=mauro --password=xxxxxx --url=https://libraries.dev2.cloud.local/artifactory/
[Thread 0] Uploading artifact: https://libraries.dev2.cloud.local/artifactory/hass_rpms/apache-tomcat-8.0.32-5.noarch.rpm
panic: Put https://libraries.dev2.cloud.local/artifactory/hass_rpms/apache-tomcat-8.0.32-5.noarch.rpm: x509: certificate signed by unknown authority
goroutine 9 [running]:
github.com/jfrogdev/jfrog-cli-go/utils/cliutils.CheckError(0x7f4c1b17c118, 0xc82041d4d0)
	/home/travis/gopath/src/github.com/JFrogDev/jfrog-cli-go/Godeps/_workspace/src/github.com/jfrogdev/jfrog-cli-go/utils/cliutils/utils.go:26 +0x4b
github.com/jfrogdev/jfrog-cli-go/utils/ioutils.Send(0x88e328, 0x3, 0xc82038cea0, 0x5a, 0x0, 0x0, 0x0, 0x101, 0xc820011be0, 0x5, ...)
......

I think it's still a relevant issue which can limit this utility scope.

Thanks,
Mauro

**Comment by TamirHadad** [comment]
Hi @maurorappa ,
1. Can you please confirm you are using the latest CLI version ? because the log in missing some new logging we added in this version, "Pinging Artifactory..." .
2. Did you put the server certificate file under .jfrog/security as instruct in our <a href=https://www.jfrog.com/confluence/display/RTF/JFrog+CLI#JFrogCLI-UsingSelf-signedSSLCertificates> documentation </a> ?

**Comment by maurorappa** [comment]
Hi Tamir,
I trimmed to output :) 
I'm reading the documentation now, which certificate format do I need? Pem is ok?

**Comment by TamirHadad** [comment]
Yes, It should work with pem.

**Comment by maurorappa** [comment]
Tamir, it's working as expected!! Super! Thanks!

**Comment by prrrajkumar** [comment]
Hello, 
I tried the same, have imported the certificate files to the security folder, and when i tried to connect i still get this error message " x509: certificate signed by unknown authority" can you support
