### ISSUE TITLE
Support --api_only=false for bintray access key creation

### ISSUE THREAD

**Issue by gschueler** [JFrogDev/jfrog-cli-go#35]
The `bt access-keys create` doesn't provide api_only flag

**Comment by eyalbe4** [comment]
Thanks @gschueler. 
We'll add this option to the *bt access-keys create* command.

**Comment by romangurevitch** [comment]
@gschueler, JFrog CLI 1.10.0 has been released and includes the --api-only flag to access key creation in Bintray.
You can also use the new JFrog CLI documentation using the following command:
`jfrog bt access-keys --help`

**Comment by eyalbe4** [comment]
@gschueler, with your permission, I'm closing this issue.

**Comment by gschueler** [comment]
👍  thanks
