### ISSUE TITLE
jfrog bt: indicate which version is published/unpublished

### ISSUE THREAD

**Issue by NicolasRouquette** [JFrogDev/jfrog-cli-go#36]
Currently, the web interface shows whether there are unpublished package versions that require manual publishing (see: https://bintray.com/docs/usermanual/uploads/uploads_managinguploadedcontent.html#_publishing)

From the CLI (version 1.4.1), it seems that there is no way to determine this information.
That is, I would expect that either `jfrog bt ps` or `jfrog bt vs` would somehow include a field in the JSon result indicating whether a particular version is published or not. 

The JSon I get from published vs. unpublished package versions is structurally equivalent.
I suggest adding a field in the JSon result specifically for this information.

**Comment by eyalbe4** [comment]
Sorry for the delayed response @NicolasRouquette.
We're currently looking into adding this information to the JSON response returned by Bintray to JFrog CLI.

**Comment by NicolasRouquette** [comment]
@eyalbe4 Glad to hear it!

**Comment by eyalbe4** [comment]
@NicolasRouquette, 
The JSON response returned from Bintray for the *jfrog bt vs* command now includes a new boolean *published* value.

**Comment by NicolasRouquette** [comment]
Thanks @eyalbe4! This works great.
