### ISSUE TITLE
CLI Artifactory command should allow to provide Principal field to build info

### ISSUE THREAD

**Issue by krihelis** [JFrogDev/jfrog-cli-go#38]
In Artifactory CLI there is a command for publishing build info to Artifactory. It is Build Integration - Publish Build (build-publish). Currently, it does not allow to provide build principal - the person who run the build. As a result of this user who is used by CLI to authenticate to artifactory is used to populate build info information - fields Principal and Artifactory Principal.

**Comment by romangurevitch** [comment]
@krihelis ,
JFrog CLI 1.10.0 has been released, publishing build-info using JFrog CLI will now add the current username as principle to the published build-info.

**Comment by eyalbe4** [comment]
@krihelis,
With you permission, I'm closing this issue.

**Comment by kerrhome** [comment]
So, is it just the env var "$username" that needs to be set?

**Comment by ajjaiah-n1234** [comment]
> @krihelis ,
> JFrog CLI 1.10.0 has been released, publishing build-info using JFrog CLI will now add the current username as principle to the published build-info.

If this is implemented, please tell us how to use it while publishing the build using jfrog CLI.

Below is command how I am trying to build publish info captured in via bce (build collect enviroment details) command
jfrog rt bp {buildName} {buildNumber} --env-exclude="*"

Please provide us how to utilize & set.

Principal & Artifactory Principal details in the Build.


thanks

**Comment by larsskj** [comment]
This is still an issue: `artifactoryPrincipal` is set, but not `principal`.
