### ISSUE TITLE
CLI delete returns 'x509: certificate signed by unknown authority' when using self-signed certificate 

### ISSUE THREAD

**Issue by andreikom** [JFrogDev/jfrog-cli-go#39]
Steps to reproduce:

1. Import your self-signed certificate to ~/.jfrog/security/cert.pem
2. Test file upload/download against a configured SSL-backed Artifactory server
3. Try to remove a file using the 'del' command arguement:

$ jfrog rt del libs-release-local/org/test/artifact.jar

And you will get an error complaining about a self signed certificate being signed by an unknown authority:

[Info] Searching artifacts...
[Error] Post https://artifactory.art.local/artifactory/api/search/aql: x509: certificate signed by unknown authority_

Version: "jfrog version 1.7.1"

**Comment by eyalbe4** [comment]
@andreikom, [this](https://github.com/JFrogDev/jfrog-cli-go/commit/520815524c7411437235149ec8e4e73525853fb3) commit to the *dev* branch fixes the issue. 
The fix will be included in the next release.

**Comment by TamirHadad** [comment]
@andreikom, JFrog CLI 1.8.0 has been released and includes a fix for this issue.

**Comment by andreikom** [comment]
Thank you!

**Comment by solvingj** [comment]
Currently getting this on `jfrog version 1.14.0`
