### ISSUE TITLE
Download fails through virtual repo

### ISSUE THREAD

**Issue by jgeorgeson** [JFrogDev/jfrog-cli-go#4]
I have a virtual repo to aggregate Maven Central and our internal Maven artifacts. There is a settings.xml deployed in a local repo that is included in the virtual repo. Downloading the settings.xml with jfrog-cli finds no artifacts using the virtual repo, but succeeds using the actual repo. Downloading from the virtual repo with curl works fine.

```
C:\Users\jgeorgeson\Downloads
> jfrog rt download maven-virtual/settings.xml
Pinging Artifactory...
Searching Artifactory using AQL query: items.find({"repo": "maven-virtual","$or": [{"$and": [{"path": {"$match":"*"},"name":{"$match":"settings.xml"}}]}]})
Artifactory response: 200 OK
Downloaded 0 artifacts from Artifactory.

C:\Users\jgeorgeson\Downloads
> jfrog rt download maven-local/settings.xml
Pinging Artifactory...
Searching Artifactory using AQL query: items.find({"repo": "maven-local","$or": [{"$and": [{"path": {"$match":"*"},"name":{"$match":"settings.xml"}}]}]})
Artifactory response: 200 OK
[Thread 0] Downloading http://artprod.example.com/artifactory/maven-local/settings.xml
[Thread 0] Artifactory response: 200 OK
Downloaded 1 artifacts from Artifactory.

C:\Users\jgeorgeson\Downloads
> curl -u jgeorgeson http://artprod.example.com/artifactory/maven-virtual/settings.xml -o settings2.xml
Enter host password for user 'jgeorgeson':
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3831  100  3831    0     0  40755      0 --:--:-- --:--:-- --:--:-- 81510

C:\Users\jgeorgeson\Downloads
> fc settings.xml settings2.xml
Comparing files settings.xml and SETTINGS2.XML
FC: no differences encountered


C:\Users\jgeorgeson\Downloads
>
```

**Comment by eyalbe4** [comment]
Thanks for reporting this @jgeorgeson. We can fix this easily by skipping the AQL search when you're requesting a download of a single file (in your case the settings.xml). We will add this to the next release.

**Comment by mgherman** [comment]
I have a similar issue when trying to download artefacts, based on a property search. It works fine against a single, local repo, however fails when searching a virtual repo that comprises two local repos.

**Comment by eyalbe4** [comment]
@mgherman, we opened [RTFACT-9870](https://www.jfrog.com/jira/browse/RTFACT-9870) so that Artifactory can support AQL searches on virtual repositories. Currently, as you can see in the CLI's console output, Artifactory returns 0 results for the AQL query sent.
Artifactory should have this support during Q2 of this year and as a result, the CLI should be able to download from virtual repositories.
In addition to that, as mentioned in this thread, from next CLI release, the AQL search will be skipped from downloads of a single file, enabling you to download the file from a virtual repository.

**Comment by eyalbe4** [comment]
Just wanted to update that the work on supporting AQL swatches on Virtual Repositories is already in progress. We'd like to have this released soon.

**Comment by eyalbe4** [comment]
Version 1.2.0 is released and includes the following:
In case of a single file download, the AQL search is skipped and you can therefore download from a Virtual Repository. Once [RTFACT-9870](https://www.jfrog.com/jira/browse/RTFACT-9870) is implemented in Artifactory, this issue will be completely resolved.

**Comment by eyalbe4** [comment]
@mgherman, @jgeorgeson and all, version 4.8.1 of Artifactory includes this capability and enables downloading from a Virtual Repository using the CLI.

**Comment by jgeorgeson** [comment]
Awesome! thanks!
