### ISSUE TITLE
CLI should support argument for specifying config file

### ISSUE THREAD

**Issue by jfrisvold** [JFrogDev/jfrog-cli-go#45]
At the moment, jfrog cli assumes the config file is located in ~/.jfrog/jfrog-cli.conf.  We'd like to use this tool in our build system, but we need to be able to specify where the config file is.  I don't see a way to do that.  It appeared that setting $HOME may do it, but upon testing, it failed.

**Comment by eyalbe4** [comment]
@jfrisvold, version 1.8.0, which has been recently released, supports configuring multiple Artifactory servers using the *rt config* command. Can this new functionality apply to your use case? I(n case it does not, can you please share your use case?

**Comment by jfrisvold** [comment]
That wouldn't work for me..  I'm using the jfrog cli in conjunction with Gitlab CI to push artifacts into artifactory.  Because we're using fresh docker containers in the builds each time, the jfrog config isn't set up in the users home directory.  So, I have a jfrog file that is pulled in via a host mount and is made available.  I just have to copy that file to the proper location in the home directory before I'm able to use it with jfrog.  Would be easier if I could just do something like this : 

`jfrog -c /path/to/jfrog.conf rt u <artifact> <repository>`

**Comment by jgeorgeson** [comment]
Same position as @jfrisvold on this. Would be great to have CI deploy the file to a clean build workspace on-the-fly without relying on it being pre-configured in user home directory. It would work really well in unison with the `--server-id` to automate complex AQL spec file promotion of artifacts to between Artifactory servers.

**Comment by larrycai** [comment]
Yes, I had similar case to be used in docker environment and preferred to have directory ( `~/.jfrog` ) independent.

**Comment by eyalbe4** [comment]
@larrycai and @jgeorgeson,
The recent CLI releases support a new environment variable named *JFROG_CLI_HOME* with a default value of *~/.jfrog*, allowing you to set JFrog CLI's home directory.

**Comment by larrycai** [comment]
Thanks.

**Comment by eyalbe4** [comment]
@jfrisvold, @larrycai and @jgeorgeson,
I'm closing this issue. Please let us know if you need further assistance with this.
