### ISSUE TITLE
Incomplete help for 'rt config'

### ISSUE THREAD

**Issue by sijis** [JFrogDev/jfrog-cli-go#46]
I downloaded the latest jfrog and the `jfrog rt config --help` output does not reflect the 'server-id' parameter that now appears to be required.

```
$ ./jfrog rt config --help
NAME:
   jfrog rt config - Configure Artifactory details.

USAGE:
   jfrog rt config [command options] [arguments...]

OPTIONS:
   --interactive 	[Default: true] Set to false if you do not want the config command to be interactive. If true, the --url option becomes optional.
   --enc-password 	[Default: true] If set to false then the configured password will not be encrypted using Artifatory's encryption API.
   --url 		[Optional] Artifactory URL.
   --user 		[Optional] Artifactory username.
   --password 		[Optional] Artifactory password.
   --apikey 		[Optional] Artifactory API key.
   --ssh-key-path 	[Optional] SSH key file path.

$./jfrog -v
jfrog version 1.8.0
```

I see the new parameter here:
https://github.com/JFrogDev/jfrog-cli-go/blob/356aefb5fa6a9b64cbbeb9476a6ee89eab1fe063/artifactory/cli.go#L170

I don't know enough Go to make a valid PR.

**Comment by eyalbe4** [comment]
@sijis, 
The *server ID* is passed to the *rt config* command as an argument and not as a command option.
See the [command documentation](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-Configuration) for more details. Currently the *--help* option shows only options and does not show arguments. We are planning to add this functionality as part of one for the upcoming releases.

**Comment by eyalbe4** [comment]
@sijis, with your permission, I'm closing this issue for now.
