### ISSUE TITLE
jfrog rt delete with --quiet not working

### ISSUE THREAD

**Issue by calexandre** [JFrogDev/jfrog-cli-go#49]
I'm setting a cron job to automatically delete artifacts based on a spec, but I need to perform this operation without confirmation. Apparently the --quiet option is not working and it is apparently ignoring my spec...

I am using jfrog-cli 1.8.0

**The following command will produce a list of artifacts to be deleted and in the end it asks for permission to delete the above paths:**
```
$ jfrog rt delete --spec /usr/share/artifactory-curator/delete-aql.json

# list of artifacts starting here
(...)
Are you sure you want to delete the above paths? (y/n)
```

**I've tried to use the --quiet to suppress the confirmation, but it is not working, it just displays the following message:**
```
$ jfrog rt delete --quiet --spec /usr/share/artifactory-curator/delete-aql.json

[Info] Searching artifacts...
[Info] Found 0 artifacts.
```

Am I missing something here?
Thanks

**Comment by calexandre** [comment]
Just found out the problem. Apparently we have to specify the flag's value (I thought that the presence of the flag itself was sufficient).

**The working command is:**
```
$ jfrog rt delete --quiet=true --spec /usr/share/artifactory-curator/delete-aql.json
# list of artifacts starting here
(...)
[Info] Deleted XXX items.
```

**Comment by weakcamel** [comment]
The same is happening for --flat flag, however --dry-run flag needs no value.
So inconsistent; perhaps this should be revisited by JFrog people after all?

**Comment by SimonaAlina** [comment]
Hi. I am using the following command in my mac groovy script:
`def stdout = sh(returnStdout: true, script: "jfrog rt del --url=${_url} --quiet=true --spec=${_specFile} --apikey=${API_KEY}")`
but the confirmation is still in the output. Here is an example of output:

T```
he CLI commands require the Artifactory URL and authentication details
Configuring JFrog CLI with these parameters now will save you having to include them as command options.
You can also configure these parameters later using the 'config' command.
Configure now? (y/n): [
  {
    "path": "myPath"
  }
]
```

I installed the jfrog cli using: `brew install jfrog-cli-go`
So, what is the problem?Thank you!

**Comment by yahavi** [comment]
@SimonaAlina 
The `--quiet` flag is only used to skip the delete confirmation message.
In order to avoid prompting 'first time configuration', please set `JFROG_CLI_OFFER_CONFIG` environment variable to false. 
For more information see [environment variables documentation](https://www.jfrog.com/confluence/display/CLI/JFrog+CLI#JFrogCLI-EnvironmentVariables).

**Comment by akhakpouri** [comment]
I'm also trying to automate the `delete` operation in an ansible playbook. I've also used `--quiet=true` in order to skip the confirmation message; however, when I run this task, it hangs.

PS - when i run this command manually in the remote server, it works fine.

```yaml
- name: Delete Artifacts
  ansible.builtin.shell:
    cmd: jf rt del --quiet=true --spec {{ query_path|quote}}/repo.spec
```
