### ISSUE TITLE
Explode uploaded archive

### ISSUE THREAD

**Issue by jgeorgeson** [JFrogDev/jfrog-cli-go#5]
It'd be great to use this tool to upload a zip to be exploded in a sub-path of a repo, rather than using Curl or using the UI Deploy to a dummy repo then moving the content to the real sub-path location (since the UI doesn't take a sub-path argument when deploying from an archive).

**Comment by eyalbe4** [comment]
Thanks @jgeorgeson. We'll make sure to implement this in one of the next releases.

**Comment by eyalbe4** [comment]
@jgeorgeson, version 1.7.0 which has been recently released added a *--explode* option to the Artifactory *upload* command, allowing you to extract archives after they are uploaded.

**Comment by eyalbe4** [comment]
@jgeorgeson, with your permission, I'm closing this issue.
