### ISSUE TITLE
Artifactory response: 403 Forbidden

### ISSUE THREAD

**Issue by MarcJose** [JFrogDev/jfrog-cli-go#53]
Hello,
I started Artifactory via
```
docker run --name artifactory -d -v `pwd`/artifactory:/var/opt/jfrog/artifactory -p 8081:8081 -e START_TMO=240 docker.bintray.io/jfrog/artifactory-oss:latest
```
went to localhost:8081 and changed the admin password. Now when I try using JFrog CLI to upload (or delete) artifacts with
`./jfrog rt u --url=http://localhost:8081 --user=admin --password=bla Downloads/maven-source-plugin-3.0.1.jar http://localhost:8081`
I receive the following error:

> [Info] [Thread 2] Uploading artifact: Downloads/maven-source-plugin-3.0.1.jar
> [Error] [Thread 2] Artifactory response: 403 Forbidden
> <h1>HTTP Status 403 - </h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>Access to the specified resource has been forbidden.</u></p><hr class="line"><h3>Apache Tomcat/8.0.41</h3>
> [Error] [Thread 2] Artifactory response: 403 Forbidden
> <h1>HTTP Status 403 - </h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>Access to the specified resource has been forbidden.</u></p><hr class="line"><h3>Apache Tomcat/8.0.41</h3>
> [Info] Uploaded 0 artifacts.
> [Error] Failed uploading 1 artifacts.

Uploading via the web interface does work but is not what I am currently needing.
Any ideas?

P.s.: Also, running `/jfrog rt c` results in:                                                                                                                                    
> Artifactory URL: http://localhost:8081
> Artifactory server ID: test
> API key (leave empty for basic authentication): 
> User: admin
> Password: [Info] Encrypting password...
> [Error] 
> Artifactory response: 404 Not Found

**Comment by MarcJose** [comment]
Oh damn, my fault...
I should add a repo and not a url...

**Comment by ackris** [comment]
@MarcJose 

Hi 

I am getting 403 on trying to do docker login. Please refer to this [issue](https://github.com/moby/moby/issues/37669). 

Were you able to resolve 403 issue?

Regards
Aditya

**Comment by MarcJose** [comment]
@ackris the problem in my case was that I used an URL instead of the repo name. Fixing that:

`./jfrog rt u --url=http://127.0.0.1:8081/artifactory --user=admin --password=password test/file.jar test`

solved all issues for me.
