### ISSUE TITLE
bt version-create --vcs-tag=TAG doesn't work

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [JFrogDev/jfrog-cli-go#55]
See for example: https://travis-ci.org/leandro-lucarella-sociomantic/ebtree/jobs/234886046#L283

```
+ jfrog bt version-create --user=[secure] --key=[secure] --desc="This is YET yet another YET test release" --vcs-tag="v6.0.socio7-will.be.removed15" --released="2017-05-22T18:12:52.000Z" sociomantic-tsunami/ebtree/ebtree/v6.0.socio7-will.be.removed15
[Info] Creating version...
[Info] Created version v6.0.socio7-will.be.removed15, details:
{
  "name": "v6.0.socio7-will.be.removed15",
  "desc": "This is YET yet another YET test release",
  "package": "ebtree",
  "repo": "ebtree",
  "owner": "sociomantic-tsunami",
  "labels": [],
  "published": false,
  "attribute_names": [],
  "created": "2017-05-22T16:16:40.973Z",
  "updated": "2017-05-22T16:16:40.982Z",
  "released": "2017-05-22T18:12:52.000Z",
  "ordinal": 4.0,
  "github_release_notes_file": null,
  "github_use_tag_release_notes": false,
  "vcs_tag": null
}
```

**Comment by eyalbe4** [comment]
Thanks for reporting this @leandro-lucarella-sociomantic .
We'll look into this issue.

**Comment by romangurevitch** [comment]
@leandro-lucarella-sociomantic ,
Thanks for reporting this, we have fixed the issue and it will be available with our next JFrog CLI release.

**Comment by romangurevitch** [comment]
@leandro-lucarella-sociomantic , 
JFrog CLI 1.10.0 has been released and includes a fix for this issue.
You can also use the new JFrog CLI documentation using the following command:
`jfrog bt version-create --help`

**Comment by eyalbe4** [comment]
@leandro-lucarella-sociomantic,
Please let us know if this issue can be closed.

**Comment by eyalbe4** [comment]
@leandro-lucarella-sociomantic, I'm closing this issue for now.

**Comment by leandro-lucarella-sociomantic** [comment]
Sorry, I haven't seen the message. I will test and reopen if I find any remaining issues! Thanks!
