### ISSUE TITLE
CLI crashes on URLs with special characters

### ISSUE THREAD

**Issue by karangurnani** [JFrogDev/jfrog-cli-go#6]
If the URL has special characters like %, #, $, CLI crashes with error invalid URL escape for either download or upload. 

As per [RTFACT-9569](https://www.jfrog.com/jira/browse/RTFACT-9569), 

> When trying to upload a file which has the name 'Test1%2.txt':
> 
> jfrog rt u Test1%2.txt libs-release-local --url=http://localhost:8081/artifactory --user=admin --password=password
> [Thread 0] Uploading artifact: http://localhost:8081/artifactory/libs-release-local/Test1%2.txt
> panic: parse http://localhost:8081/artifactory/libs-release-local/Test1%2.txt: **invalid URL escape "%2."**
> goroutine 5 [running]:
> github.com/jfrogdev/jfrog-cli-go/cliutils.CheckError(0x8820916b50, 0x8207757d0)
> /home/travis/gopath/src/github.com/JFrogDev/jfrog-cli-go/Godeps/_workspace/src/github.com/jfrogdev/jfrog-cli-go/cliutils/utils.go:26 +0x4b
> github.com/jfrogdev/jfrog-cli-go/cliutils.UploadFile(0x820792038, 0x820772b40, 0x40, 0x820771530, 0x5, 0x820771550, 0x8, 0x8207757a0, 0x0)
> /home/travis/gopath/src/github.com/JFrogDev/jfrog-cli-go/Godeps/_workspace/src/github.com/jfrogdev/jfrog-cli-go/cliutils/ioutils.go:180 +0x148
> github.com/jfrogdev/jfrog-cli-go/artifactory/utils.UploadFile(0x820792038, 0x820772b40, 0x40, 0x820777270, 0x820775680, 0x0)
> /home/travis/gopath/src/github.com/JFrogDev/jfrog-cli-go/Godeps/_workspace/src/github.com/jfrogdev/jfrog-cli-go/artifactory/utils/artifactoryutils.go:26 +0x1f6
> github.com/jfrogdev/jfrog-cli-go/artifactory/commands.uploadFile(0x7fff5fbffb4d, 0xb, 0x820772b40, 0x40, 0x82077c180, 0x8207716b0, 0xa, 0x0)
> /home/travis/gopath/src/github.com/JFrogDev/jfrog-cli-go/Godeps/_workspace/src/github.com/jfrogdev/jfrog-cli-go/artifactory/commands/upload.go:141 +0x485
> github.com/jfrogdev/jfrog-cli-go/artifactory/commands.Upload.func1(0x82077c180, 0x1, 0x82076f3e0, 0x1, 0x1, 0x82076f400, 0x3, 0x3, 0x820771670, 0x0)
> /home/travis/gopath/src/github.com/JFrogDev/jfrog-cli-go/Godeps/_workspace/src/github.com/jfrogdev/jfrog-cli-go/artifactory/commands/upload.go:38 +0x13d
> created by github.com/jfrogdev/jfrog-cli-go/artifactory/commands.Upload
> /home/travis/gopath/src/github.com/JFrogDev/jfrog-cli-go/Godeps/_workspace/src/github.com/jfrogdev/jfrog-cli-go/artifactory/commands/upload.go:43 +0x1e3

**Comment by karangurnani** [comment]
I've a potential fix, for both upload and download.

[commands.zip](https://github.com/JFrogDev/jfrog-cli-go/files/232658/commands.zip)

**Comment by eyalbe4** [comment]
Thanks @karangurnani. We'll check this soon and will definitely have this fixed in the coming release.

**Comment by eyalbe4** [comment]
@karangurnani, Version 1.2.0 has been released and includes a fix for this issue.
