### ISSUE TITLE
cli re-downloads file even if it was already downloaded

### ISSUE THREAD

**Issue by itamarb** [JFrogDev/jfrog-cli-go#64]
If you download a file from Artifactory and rename it, then run the same command again, the cli re-downloads the file, since the aql query returns results of a file with a different name than what the client has.
To reproduce:
Run the download command with a rename of the downloaded file twice:
jfrog rt dl --url http://mill.jfrog.info:12047/artifactory example-repo-local/situationalawareness-0.0.8.aar ~/Sandbox/test/test.aar

**Comment by romangurevitch** [comment]
@itamarb,
Thanks for reporting this, we have fixed the issue and it will be available with our next JFrog CLI release.

**Comment by romangurevitch** [comment]
@itamarb ,
JFrog CLI 1.10.0 has been released and includes a fix for this issue.

**Comment by eyalbe4** [comment]
@itamarb,
Can this issue be closed?

**Comment by eyalbe4** [comment]
@itamarb,
I'm closing this issue. Please let us know in case you need further assistance.
