### ISSUE TITLE
Download failed if folder name contain the character ':' in Windows

### ISSUE THREAD

**Issue by yudkeh** [JFrogDev/jfrog-cli-go#65]
Since the character ':' is forbidden in Windows folder name, in case we try to download to folder which it name contain the character ':' the download will fail.

for example:
if our build name contain  the character ':', for example "myBuild:test", in case we will try to download the entire build we will get the following error:

jfrog rt dl * --server-id ArtifactoryOL --build-name="myBuild:test" --build-number LATEST .
[Error] mkdir C:\Users\yehudah\AppData\Local\Temp/jfrog/builds/myBuild:test_LATEST/: The directory name is invalid.

step to reproduce:
1. create build with the character ':' in it name.
2. try to download the artifact according to the following command:
`jfrog rt dl * --server-id <server id> --build-name="<build name>" --build-number LATEST .`

**Comment by romangurevitch** [comment]
@yudkeh,
JFrog CLI 1.10.0 has been released and includes a fix for this issue.

**Comment by eyalbe4** [comment]
@yudkeh, 
May we close this issue?

**Comment by eyalbe4** [comment]
@yudkeh, I'm closing this issue for now.
