### ISSUE TITLE
https with self signed cert

### ISSUE THREAD

**Issue by judavi** [JFrogDev/jfrog-cli-go#66]
Hello, I'm using https with a custom certificate but I'm getting an error (https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-UsingSelf-signedSSLCertificates)

Version:
`C:\Users\judavi\Desktop\jfrog>jfrog -v `

jfrog version 1.9.0

Command:
`C:\Users\judavi\Desktop\jfrog>jfrog rt u test.txt test/notary/ 
-url=https://www.myurl.com/artifactory --user=myuser --password=xxxxxxxx `

Error:
[Info] [Thread 2] Uploading artifact: test.txt
[Error] Put https://www.myurl.com/test/notary/test.txt: x509: certificate signed by unknown authority

Pem:

![image](https://user-images.githubusercontent.com/1766933/27323969-7385c79c-559b-11e7-8335-06e77bcf145a.png)

Any thoughts?
@TamirHadad 

Thanks!

**Comment by eyalbe4** [comment]
@judavi,
Sorry for not responding to your question yet. We'll reply soon.

**Comment by TamirHadad** [comment]
@judavi,
We have test this functionality and it works fine for us.
We used this command to create our certificates:
```
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365
```
In addition, we are looking into a way to add an automated test for using self-sign certificates.

**Comment by eyalbe4** [comment]
@judavi,
Since version 1.11.1, the CLI's integration tests include a test which sets up a reverse proxy server and creates a self signed certificate for it. The test then tries to run commands using the certificate.
The README file includes instructions for how to run the tests.
This test can be used to troubleshoot certificate issues.

**Comment by eyalbe4** [comment]
@judavi,
Please let us know if you need further help. I'm closing this issue for now.
