### ISSUE TITLE
Whitespace is stripped out of build name in file spec

### ISSUE THREAD

**Issue by darwish** [JFrogDev/jfrog-cli-go#74]
I have a file spec that looks like this:
```json
{
    "files": [
        {
            "aql": {
                "items.find": {
                    "@build.name": "myproject :: mybranch"
                }
            }
        }
    ]
}
```
This naming convention for builds comes from the [Artifactory Plugin for Jenkins](https://github.com/jenkinsci/artifactory-plugin/blob/63858aca182ee2aa4bbb12548d167392ec7affed/src/main/java/org/jfrog/hudson/util/BuildUniqueIdentifierHelper.java#L135)

If I use the cli to do a search, the whitespace seems to get removed from my query:
```bash
$ JFROG_CLI_LOG_LEVEL=DEBUG jfrog rt s --spec filespec.json
[Info] Searching artifacts...
[Debug] Searching Artifactory using AQL query:  items.find({"@build.name":"myproject::mybranch"}).include("name","repo","path","actual_md5","actual_sha1","size","property","type")
```
which obviously doesn't find what I'm looking for.

The issue seems to be at https://github.com/JFrogDev/jfrog-cli-go/blob/c1b328e6667df562f4d774bdbd2b1826dc485a66/artifactory/utils/specutils.go#L52. I can confirm that replacing `aql.ItemsFind = cliutils.StripChars(str[first:last], "\n\t ")` with `aql.ItemsFind = str[first:last]` fixes the issue, although it loses all minification entirely:
```bash
$ JFROG_CLI_LOG_LEVEL=DEBUG ./jfrog rt s --spec ~/code/testengine/tts/filespec.json
[Info] Searching artifacts...
[Debug] Searching Artifactory using AQL query:  items.find( {
                    "@build.name": "myproject :: mybranch"
                }
            ).include("name","repo","path","actual_md5","actual_sha1","size","property","type")
```

**Comment by eyalbe4** [comment]
Thanks for reporting this @darwish.
We'll work on fixing this and keep you posted.

**Comment by yahavi** [comment]
Thanks, @darwish.
We fixed this issue. 
Here is the link to the commit: https://github.com/JFrogDev/jfrog-cli-go/commit/3cbce8c3e0950307ca5f1c9e4f54815ef45ff5bc

**Comment by eyalbe4** [comment]
@darwish,
Version 1.10.2 is released and includes this fix.
