### ISSUE TITLE
(1.10.1) Invalid CIDR response to access key creation

### ISSUE THREAD

**Issue by salazar** [JFrogDev/jfrog-cli-go#75]
Running `jfrog bt acc-keys --user USER --key KEY --org ORG create` -- where USER, KEY, and ORG are placeholders for my actual values :) -- gives me the following error on version `1.10.1`; works properly on `1.9.0`:

```
[Info] Creating access key...
[Error] Bintray response: 400 Bad Request
{
  "message": "Invalid CIDR ."
}
```

Edit: Mac distribution.

**Comment by salazar** [comment]
The problem appears to be in `bintray/commands/accesskeys.go`, function `BuildAccessKeyJson`. If either `--white-cidrs` or `--black-ciders` is empty, the splits on line 98 and 99 will result in a 1-element slice -- an empty slice wouldn't cause it. I suspect something like the following should be a correct solution:

```
diff --git a/bintray/commands/accesskeys.go b/bintray/commands/accesskeys.go
index 4720183..c54267d 100644
--- a/bintray/commands/accesskeys.go
+++ b/bintray/commands/accesskeys.go
@@ -92,11 +92,21 @@ func BuildAccessKeyJson(flags *AccessKeyFlags) (string, error) {
 		return "", err
 	}
 
+	var whiteCidrsSplit []string
+	if flags.WhiteCidrs != "" {
+		whiteCidrsSplit = strings.Split(flags.WhiteCidrs, ",")
+	}
+
+	var blackCidrsSplit []string
+	if flags.BlackCidrs != "" {
+		blackCidrsSplit = strings.Split(flags.BlackCidrs, ",")
+	}
+
 	data := AccessKeyConfig{
 		Id:             flags.Id,
 		Expiry:         flags.Expiry,
-		WhiteCidrs:     strings.Split(flags.WhiteCidrs, ","),
-		BlackCidrs:     strings.Split(flags.BlackCidrs, ","),
+		WhiteCidrs:     whiteCidrsSplit,
+		BlackCidrs:     blackCidrsSplit,
 		ApiOnly:        apiOnly,
 		ExistenceCheck: ExistenceCheckConfig{
 			Url:             flags.ExistenceCheckUrl,
```

**Comment by romangurevitch** [comment]
@salazar, 
Thanks for reporting this issue, 
We will look at this issue and report soon.

**Comment by eyalbe4** [comment]
@salazar,
We found and fixed the issue. We'll soon release a fix.
We'll let you know once it is released.

**Comment by eyalbe4** [comment]
@salazar,
Version 1.10.2 has been released and includes the fix for this Issue. 
We'd appreciate your feedback for it.

**Comment by salazar** [comment]
Thanks for letting me know @eyalbe4. Closing this issue.
