### ISSUE TITLE
Add ability to bypass the offer to create configuration

### ISSUE THREAD

**Issue by medzin** [JFrogDev/jfrog-cli-go#8]
Please add ability to bypass (for example with -silent flag) the offer to create configuration for CLI. I mean this code:
https://github.com/JFrogDev/jfrog-cli-go/blob/master/artifactory/cli.go#L394-L400

It is very annoying when you use the CLI in bash scripts on CI.

**Comment by eyalbe4** [comment]
Thanks for the feedback @medzin. We'll make sure to include an option to skip this message in the next release. As a temporary workaround, you can run the config command with --interactive=false at the beginning of your script.

**Comment by eyalbe4** [comment]
@medzin, version 1.3.2 of the CLI adds this ability, by setting the *JFROG_CLI_OFFER_CONFIG* environment variable to *false*.

**Comment by medzin** [comment]
@eyalbe4 Thanks!
