### ISSUE TITLE
How to exclude [md5] files from recursive upload?

### ISSUE THREAD

**Issue by jgeorgeson** [JFrogDev/jfrog-cli-go#81]
I have a local file system full of Ivy modules that I want to upload with CLI, and it's always spouting out errors on the checksum files

```
[Info] [Thread 0] Uploading artifact: xml-security-c/HEAD/1.5.0/include/include-linux32rh6.zip
[Info] [Thread 0] Uploading artifact: xml-security-c/HEAD/1.5.0/include/include-linux32rh5.zip.md5
[Error] [Thread 0] Artifactory response: 404 Not Found
{
  "errors": [
    {
      "status": 404,
      "message": "Target file to set checksum on doesn't exist: ivy-lgc-releases:OW_5000_10_5_0_RTM/xml-security-c/HEAD/1.5.0/include/include-linux32rh5.zip"
    }
  ]
}
```

You may notice it says thread 0 for both files. Using default settings I thought multi-threading was trying to upload the md5 before the file, but setting `--threads=0` shows no change. I tried doing a regexp upload with `--regexp=true '.*(?!\.md5)'` but apparently Go language doesn't support negative lookahead. :/

Am I imagining that the upload command used to support `--include` and `--exclude` arguments? How do I exclude files?

**Comment by eyalbe4** [comment]
@jgeorgeson,
No the *upload* command has not supported the exclusion of files, buy we're actually working right now on adding exclude patterns to the File Specs schema. This will allow you to easily exclude md5 or any other file type by using a wildcard pattern.

**Comment by jgeorgeson** [comment]
Awesome. One suggestion on the `--regexp` feature, provide documentation of the supported regex syntax (is it Google re2?).

**Comment by eyalbe4** [comment]
@jgeorgeson,

Version 1.11.1 has been recently released and allows defining a list of exclude patterns for most of the Artifactory commands. 

Exclude patterns can be either defined in File Specs or as a command option. See the documentation for more details.

Also following your suggestion, we'll add a note in the documentation saying that the regular expressions supported by the *upload* command use the *golang* syntax.

**Comment by jgeorgeson** [comment]
thanks, I will download and test.

**Comment by eyalbe4** [comment]
@jgeorgeson,
I'm closing this one for now. Please let us know if you need help with this.
