### ISSUE TITLE
it did not fail with exit code=1

### ISSUE THREAD

**Issue by mh-cbon** [JFrogDev/jfrog-cli-go#87]
Hi,

I run in a case where the binary reported an error, but exited with code=0

It would be preferable it fails with code=1

The problem was a wrong filename (deb file was not found), in my understanding.

https://travis-ci.org/mh-cbon/go-bin-deb/jobs/268686049

```
$ ./jfrog bt upload --override=true --publish=true --deb=unstable/main/$OSARCH $APP-$OSARCH-$VERSION.deb $GH_USER/$GH_APP/$GH_APP/$VERSION pool/g/$GH_APP/

Incorrect Usage.

Name:

	jfrog bt upload - Upload files.

Usage:

	jfrog bt u [command options] <source path> <target location> [target path]

Arguments:

	source path

		The first argument specifies the local file system path to artifacts which should be uploaded to Bintray.

		You can specify multiple artifacts by using wildcards or a regular expression as designated by the --regexp command option.

		If you have specified
```

Where `$APP-$OSARCH-$VERSION.deb` was not correct (my fault), but the build did not failed as it should have.

**Comment by ortsi** [comment]
@mh-cbon , Thanks for reporting this issue. we are currently evaluating a fix the issue and it will be available in one of our next JFrog CLI releases.

**Comment by eedwardsav** [comment]
@ortsi status on this issue? Artifactory exiting with an error state but returning 0 is extremely bad...

**Comment by eyalbe4** [comment]
@eedwardsav,
We'd like to include this fix as part of the next JFrog CLI release.

**Comment by eedwardsav** [comment]
@eyalbe4 multiple releases later and I'm still seeing this issue, is it still planned for release soon? thanks!

**Comment by eyalbe4** [comment]
@eedwardsav,
[This](https://github.com/JFrogDev/jfrog-cli-go/commit/66192df946a0b489d11d0ffe532256df35c87da9) commit fixes this issue. It is already pushed into the *dev* branch and will be part of the upcoming release.

**Comment by eyalbe4** [comment]
@mh-cbon and @eedwardsav,
Version 1.13.1 includes a fix for this issue. Can you please try it out?

**Comment by eyalbe4** [comment]
@mh-cbon and @eedwardsav,
I'm closing this issue for now. We'd appreciate your feedback for it though.
