### ISSUE TITLE
Some CLI commands require the following common options:

### ISSUE THREAD

**Issue by mh-cbon** [JFrogDev/jfrog-cli-go#88]
running on travis,

```
$ ./jfrog bt pc --key=$BTKEY --user=$GH_USER --licenses=MIT --vcs-url=https://github.com/$GH_USER/$GH_APP $GH_USER/$GH_APP/$GH_APP || echo "package already exists"

Some CLI commands require the following common options:
- User
- API Key
- Default Package Licenses
Configuring JFrog CLI with these parameters now will save you having to include them as command options.
You can also configure these parameters later using the 'config' command.
Configure now? (y/n): 
```

- if there would be -y option that s cool
- if there is no such question becasue i provided al required data, that s coo too
- if detects its not a tty, thus does not ask user input, that s cool also

**Comment by eyalbe4** [comment]
@mh-cbon, if you set the value of the *JFROG_CLI_OFFER_CONFIG* environment variable to *true*, the CLI will not prompt the offer config message.
Please let us know if this helps.

**Comment by mh-cbon** [comment]
I will not say this is obvious, but yeah that helps. thanks

**Comment by Clement-TS** [comment]
Why don't you support the `--interactive false`? That would avoid later errors on the same topic...

**Comment by Kuanlin-Chen** [comment]
How to set `JFROG_CLI_OFFER_CONFIG` to false ?

**Comment by eyalbe4** [comment]
We pushed https://github.com/jfrog/jfrog-cli-go/commit/93818f536d84451d064841ca8bdc52e438340bcd, so that prompts message also suggests the option of setting the *JFROG_CLI_OFFER_CONFIG* to *false*.

@Kuanlin-Chen - *JFROG_CLI_OFFER_CONFIG* is an environment variable.
Set it to false as follows:
```export JFROG_CLI_OFFER_CONFIG=false```
or on Windows:
```set JFROG_CLI_OFFER_CONFIG=false```
