### ISSUE TITLE
https://bintray.com/docs/api/#_delete_content

### ISSUE THREAD

**Issue by mh-cbon** [JFrogDev/jfrog-cli-go#92]
is it implemented ? its unclear sorry.

**Comment by eyalbe4** [comment]
@mh-cbon,
The *Delete Content* API is not yet supported by JFrog CLI.
By running ```jfrog bt``` you'll get a list of all the existing Bintray commands.

**Comment by mh-cbon** [comment]
sure, thanks.

For future readers,

```sh
curl -X "DELETE" -u%GH_USER%:%BT_KEY% https://api.bintray.com/content/%GH_USER%/choco/%GH_APP%.%VERSION%.nupkg
```
