### ISSUE TITLE
Where is the changelog?

### ISSUE THREAD

**Issue by bendikro** [JFrogDev/jfrog-cli-go#94]
I can't find a changelog in the repo or source packages. Am I blind?

**Comment by eyalbe4** [comment]
Hi @bendikro,
The the link to the release notes is available in [Release Notes section](https://www.jfrog.com/confluence/display/CLI/JFrog+CLI#JFrogCLI-ReleaseNotes) in the main documentation page.
We'll also add a link to it in README.

**Comment by eyalbe4** [comment]
Added the Release Notes link to the README in the [*dev* branch](https://github.com/JFrogDev/jfrog-cli-go/tree/dev).

**Comment by eyalbe4** [comment]
@bendikro,
I'm closing this issue. Pleas let us know if you need further assistance.
