### ISSUE TITLE
"jfrog bt u --explode true --publish true --override true" and conflicts in exploded artifacts

### ISSUE THREAD

**Issue by NicolasRouquette** [JFrogDev/jfrog-cli-go#98]
When uploading and exploding an artifact, the "--override" flag has no effect with respect to conflicts that may arise in the *exploded* artifacts.

That is, it seems that "--override" only pertains to the *uploaded* artifact.

It would be helpful to have an option to allow overriding *exploded* artifacts.

Here's how I ran into this problem:

We use Eclipse/Tycho to build and publish to bintray Eclipse P2 update sites as ZIP archives.
Here's an example:

https://bintray.com/jpl-imce/gov.nasa.jpl.imce.oml/download_file?file_path=gov%2Fnasa%2Fjpl%2Fimce%2Foml%2Fgov.nasa.jpl.imce.oml.updatesite%2F0.9.0.0-M02%2Fgov.nasa.jpl.imce.oml.updatesite-0.9.0.0-M02.zip

To be useful for Eclipse, the P2 update site ZIP archive needs to be "exploded".
I've used the CLI to do this before but recently we're getting conflicts not with the ZIP archive itself but with its exploded contents:

```
jfrog bt u --explode true --publish true --override true ~/Downloads/gov.nasa.jpl.imce.oml.updatesite-0.9.0.0-M02.zip jpl-imce/gov.nasa.jpl.imce.oml/gov.nasa.jpl.imce.oml.updatesite/0.9.0.0-M02
[Info] Verifying repository gov.nasa.jpl.imce.oml exists...
[Info] Verifying package gov.nasa.jpl.imce.oml.updatesite exists...
[Info] Verifying version 0.9.0.0-M02 exists...
[Info] [Thread 0] Uploading artifact: /Users/rouquett/Downloads/gov.nasa.jpl.imce.oml.updatesite-0.9.0.0-M02.zip
[Error] [Thread 0] Bintray response: 409 Conflict
{
  "message": "Unable to upload files: An artifact with the path 'features/org.eclipse.gef_3.11.0.201606061308.jar' already exists under another version"
}
[Info] Uploaded 0 artifacts.
[Error] Failed uploading 1 artifacts.
```

There are a couple of things that are strange about this.

1) The exploded files are uploaded underneath the root of the organization, i.e., `jpl-imce/gov.nasa.jpl.imce.oml`, not underneath the package/version, i.e.: `jpl-imce/gov.nasa.jpl.imce.oml/gov.nasa.jpl.imce.oml.updatesite/0.9.0.0-M02`

2) Because of (1), the P2 contents (`features`, `plugins`) and metadata (`artifacts.jar`, `contents.jar`, `p2.index`) are exploded here:

https://dl.bintray.com/jpl-imce/gov.nasa.jpl.imce.oml/features/
https://dl.bintray.com/jpl-imce/gov.nasa.jpl.imce.oml/plugins/
https://dl.bintray.com/jpl-imce/gov.nasa.jpl.imce.oml/

3) Because of (1,2), the only legitimate P2 Eclipse Update site URL is the organization itself:
https://dl.bintray.com/jpl-imce/gov.nasa.jpl.imce.oml/

4) Since particular plugins and/or features may be reused across different versions of a P2 update site, there may be conflicts that arise when exploding the archive on upload as I've experienced.

It would be useful to have an option to allow overriding existing exploded files.

**Comment by eyalbe4** [comment]
Thanks for sharing this @NicolasRouquette.
As an alternative to the override functionality, would it be possible for you to delete the version on Bintray and recreate it with the new published content?

**Comment by eyalbe4** [comment]
@NicolasRouquette,
Were you able to try out the suggested workaround?

**Comment by NicolasRouquette** [comment]
I tried this; however, there is a caveat: one can only delete a previous OSS version if it has been published < 6 months ago (see: https://bintray.com/docs/api/#_delete_content)
Even within 6 months, I've had problems deleting & exploring a zip archive for a P2 update site.

Compared to SBT, P2 is very difficult to work with, so much so that I've effectively given up on P2.

So as far as I'm concerned, I no longer have a need for the functionality originally requested.
