### ISSUE TITLE
Self Signed SSL Directory don't working

### ISSUE THREAD

**Issue by deutschtang** [JFrogDev/jfrog-cli-go#99]
Hi:

In the latest master branch:  jfrog-cli-go/jfrog-cli/artifactory/utils/utils.go

GetJfrogSecurityDir return value is ~/.jfrogsecurity/, not "~/.jfrog/security/"  :)

**Comment by ortsi** [comment]
@deutschtang,

Thanks for reporting this issue!
We've just released 1.11.1 addressing this problem.
you're welcome to download and test.

thanks again,

**Comment by deutschtang** [comment]
Thanks, this issue is resolved in new releases :)
